# Source Generated with Decompyle++
# File: tmpl3a5fsaw.marshal (Python 3.11)

if not EditAlertDialog.objectName():
    EditAlertDialog.setObjectName('EditAlertDialog')
EditAlertDialog.resize(323, 145)
self.formLayout = QFormLayout(EditAlertDialog)
self.formLayout.setObjectName('formLayout')
self.meanHighEnabled = QCheckBox(EditAlertDialog)
self.meanHighEnabled.setObjectName('meanHighEnabled')
self.formLayout.setWidget(0, QFormLayout.LabelRole, self.meanHighEnabled)
self.meanHigh = UnitFormatterDoubleSpinBox(EditAlertDialog)
self.meanHigh.setObjectName('meanHigh')
self.meanHigh.setEnabled(False)
self.meanHigh.setMinimumSize(QSize(200, 0))
self.formLayout.setWidget(0, QFormLayout.FieldRole, self.meanHigh)
self.meanLowEnabled = QCheckBox(EditAlertDialog)
self.meanLowEnabled.setObjectName('meanLowEnabled')
self.formLayout.setWidget(1, QFormLayout.LabelRole, self.meanLowEnabled)
self.meanLow = UnitFormatterDoubleSpinBox(EditAlertDialog)
self.meanLow.setObjectName('meanLow')
self.meanLow.setEnabled(False)
self.meanLow.setMinimumSize(QSize(200, 0))
self.formLayout.setWidget(1, QFormLayout.FieldRole, self.meanLow)
self.stdHighEnabled = QCheckBox(EditAlertDialog)
self.stdHighEnabled.setObjectName('stdHighEnabled')
self.formLayout.setWidget(2, QFormLayout.LabelRole, self.stdHighEnabled)
self.stdHigh = UnitFormatterDoubleSpinBox(EditAlertDialog)
self.stdHigh.setObjectName('stdHigh')
self.stdHigh.setEnabled(False)
self.stdHigh.setMinimumSize(QSize(200, 0))
self.formLayout.setWidget(2, QFormLayout.FieldRole, self.stdHigh)
self.stdLowEnabled = QCheckBox(EditAlertDialog)
self.stdLowEnabled.setObjectName('stdLowEnabled')
self.formLayout.setWidget(3, QFormLayout.LabelRole, self.stdLowEnabled)
self.stdLow = UnitFormatterDoubleSpinBox(EditAlertDialog)
self.stdLow.setObjectName('stdLow')
self.stdLow.setEnabled(False)
self.stdLow.setMinimumSize(QSize(200, 0))
self.formLayout.setWidget(3, QFormLayout.FieldRole, self.stdLow)
self.buttonBox = QDialogButtonBox(EditAlertDialog)
self.buttonBox.setObjectName('buttonBox')
self.buttonBox.setOrientation(Qt.Horizontal)
self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel | QDialogButtonBox.Ok)
self.formLayout.setWidget(4, QFormLayout.SpanningRole, self.buttonBox)
self.retranslateUi(EditAlertDialog)
self.buttonBox.accepted.connect(EditAlertDialog.accept)
self.buttonBox.rejected.connect(EditAlertDialog.reject)
self.meanHighEnabled.toggled.connect(self.meanHigh.setEnabled)
self.meanLowEnabled.toggled.connect(self.meanLow.setEnabled)
self.stdHighEnabled.toggled.connect(self.stdHigh.setEnabled)
self.stdLowEnabled.toggled.connect(self.stdLow.setEnabled)
QMetaObject.connectSlotsByName(EditAlertDialog)
