# Source Generated with Decompyle++
# File: tmpfnipk_gy.marshal (Python 3.11)

self.timeButton.clicked.connect(self.time_analysis)
self.synchronousTimeButton.clicked.connect(self.synchronous_time_analysis)
self.overlaidTimeButton.clicked.connect(self.overlaid_time_analysis)
self.spectrogramButton.clicked.connect(self.spectrogram_analysis)
self.psdButton.clicked.connect(self.psd_analysis)
self.singleChannelPsdButton.clicked.connect(self.single_channel_psd_analysis)
self.singleSlicePsdButton.clicked.connect(self.single_slice_psd_analysis)
self.overlaidPsdButton.clicked.connect(self.overlaid_psd_analysis)
self.csvButton.clicked.connect(self.csv_export)
self.csvDownsampledButton.clicked.connect(self.csv_downsampled_export)
self.fileInformationButton.clicked.connect(self.file_information)
self.viewSettingsButton.clicked.connect(self.view_settings)
self.rawExportButton.clicked.connect(self.raw_export)
self.splitFileButton.clicked.connect(self.split_file)
self.actionPreferences.triggered.connect(self.show_preferences)
self.actionAbout.triggered.connect(self.show_about)
self.actionAboutLibraries.triggered.connect(self.show_about_libraries)
self.actionShowLogs.triggered.connect(self.show_log_dir)
self.actionUpdateLatestStable.triggered.connect(self.update_latest_stable)
self.actionUpdateCurrentBranch.triggered.connect(self.update_current_branch)
self.actionUpdateSpecificBranch.triggered.connect(self.update_specific_branch)
self.actionUpdateSpecificCommit.triggered.connect(self.update_specific_commit)
self.software_finder = hyperborea.download.SoftwareFinder(logger)
self.software_finder.completed.connect(self.update_finder_completed)
self.software_finder.error.connect(self.update_finder_error)
self.ref_finder = hyperborea.download.RefFinder(logger)
self.ref_finder.completed.connect(self.ref_finder_completed)
self.ref_finder.error.connect(self.ref_finder_error)
self.software_downloader = hyperborea.download.Downloader(logger)
self.software_downloader.update.connect(self.update_progress_cb)
self.software_downloader.completed.connect(self.software_download_completed)
self.software_downloader.error.connect(self.software_download_error)
