# Source Generated with Decompyle++
# File: tmpi9x7wepm.marshal (Python 3.11)

if not SelectSubchannelsDialog.objectName():
    SelectSubchannelsDialog.setObjectName('SelectSubchannelsDialog')
SelectSubchannelsDialog.resize(400, 49)
self.verticalLayout_2 = QVBoxLayout(SelectSubchannelsDialog)
self.verticalLayout_2.setObjectName('verticalLayout_2')
self.verticalLayout = QVBoxLayout()
self.verticalLayout.setObjectName('verticalLayout')
self.verticalLayout_2.addLayout(self.verticalLayout)
self.buttonBox = QDialogButtonBox(SelectSubchannelsDialog)
self.buttonBox.setObjectName('buttonBox')
self.buttonBox.setOrientation(Qt.Horizontal)
self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel | QDialogButtonBox.Ok)
self.verticalLayout_2.addWidget(self.buttonBox)
self.retranslateUi(SelectSubchannelsDialog)
self.buttonBox.accepted.connect(SelectSubchannelsDialog.accept)
self.buttonBox.rejected.connect(SelectSubchannelsDialog.reject)
QMetaObject.connectSlotsByName(SelectSubchannelsDialog)
