# Source Generated with Decompyle++
# File: tmp3vrlqixd.marshal (Python 3.11)

PreferencesDialog.setWindowTitle(QCoreApplication.translate('PreferencesDialog', 'Preferences', None))
self.lightMode.setText(QCoreApplication.translate('PreferencesDialog', 'Light Mode', None))
self.supplyChecksLabel.setText(QCoreApplication.translate('PreferencesDialog', 'Supply Checks', None))
self.displayModeLabel.setText(QCoreApplication.translate('PreferencesDialog', 'Display Mode', None))
self.darkMode.setText(QCoreApplication.translate('PreferencesDialog', 'Dark Mode', None))
self.showSupplyChecks.setText(QCoreApplication.translate('PreferencesDialog', 'Show supply checks in device info panel', None))
self.tabWidget.setTabText(self.tabWidget.indexOf(self.interfaceTab), QCoreApplication.translate('PreferencesDialog', 'Interface', None))
self.automaticRGBCheckBox.setText(QCoreApplication.translate('PreferencesDialog', 'Automatically set RGB LEDs when connecting/disconnecting', None))
self.ledsLabel.setText(QCoreApplication.translate('PreferencesDialog', 'RGB LEDs', None))
self.downsamplingLabel.setText(QCoreApplication.translate('PreferencesDialog', 'Downsampling (time domain graph only)', None))
self.downsampleCheckBox.setText(QCoreApplication.translate('PreferencesDialog', 'Downsample high speed channels', None))
self.plotMeanCheckBox.setText(QCoreApplication.translate('PreferencesDialog', 'Plot 1 second mean', None))
self.tabWidget.setTabText(self.tabWidget.indexOf(self.streamingTab), QCoreApplication.translate('PreferencesDialog', 'Streaming', None))
self.unitsLabel.setText(QCoreApplication.translate('PreferencesDialog', 'Display Units', None))
self.tabWidget.setTabText(self.tabWidget.indexOf(self.unitTab), QCoreApplication.translate('PreferencesDialog', 'Units', None))
self.connectivityLabel.setText(QCoreApplication.translate('PreferencesDialog', 'Connectivity', None))
self.browseButton.setText(QCoreApplication.translate('PreferencesDialog', 'Browse...', None))
self.outputLocationLabel.setText(QCoreApplication.translate('PreferencesDialog', 'Output Location', None))
self.compressionLabel.setText(QCoreApplication.translate('PreferencesDialog', 'Compression', None))
self.runModbusCheckBox.setText(QCoreApplication.translate('PreferencesDialog', 'Run Modbus TCP server (NOTE: devices must be enabled individually)', None))
self.modbusPortLabel.setText(QCoreApplication.translate('PreferencesDialog', 'Modbus TCP Port (default 502)', None))
self.compressionLevelLabel.setText(QCoreApplication.translate('PreferencesDialog', 'Compression Level (default 6)', None))
self.tabWidget.setTabText(self.tabWidget.indexOf(self.outputTab), QCoreApplication.translate('PreferencesDialog', 'Output', None))
self.eventUploadEnabled.setText(QCoreApplication.translate('PreferencesDialog', 'Enable event upload for firmware updates and calibration', None))
self.uploadSecretAccessKeyLabel.setText(QCoreApplication.translate('PreferencesDialog', 'AWS Secret Access Key', None))
self.enableUpload.setText(QCoreApplication.translate('PreferencesDialog', 'Enable AWS S3 upload', None))
self.eventUploadLabel.setText(QCoreApplication.translate('PreferencesDialog', 'Event Upload', None))
self.uploadDirectoryLabel.setText(QCoreApplication.translate('PreferencesDialog', 'Upload Directory', None))
self.awsRegionLabel.setText(QCoreApplication.translate('PreferencesDialog', 'S3 Bucket AWS Region', None))
self.s3UploadLabel.setText(QCoreApplication.translate('PreferencesDialog', 'Amazon S3 Upload', None))
self.uploadAccessKeyIDLabel.setText(QCoreApplication.translate('PreferencesDialog', 'AWS Access Key ID', None))
self.uploadDeleteOriginal.setText(QCoreApplication.translate('PreferencesDialog', 'Delete original .apd after successful upload', None))
self.s3BucketLabel.setText(QCoreApplication.translate('PreferencesDialog', 'S3 Bucket', None))
self.tabWidget.setTabText(self.tabWidget.indexOf(self.uploadTab), QCoreApplication.translate('PreferencesDialog', 'Cloud Upload', None))
self.alertEmailLabel.setText(QCoreApplication.translate('PreferencesDialog', 'Alert Email', None))
self.toAddressLabel.setText(QCoreApplication.translate('PreferencesDialog', 'To Address', None))
self.smtpUserLabel.setText(QCoreApplication.translate('PreferencesDialog', 'SMTP User', None))
self.smtpPasswordLabel.setText(QCoreApplication.translate('PreferencesDialog', 'SMTP Password', None))
self.smtpHostLabel.setText(QCoreApplication.translate('PreferencesDialog', 'SMTP Server Host', None))
self.useSSL.setText(QCoreApplication.translate('PreferencesDialog', 'SSL/TLS', None))
self.fromAddressLabel.setText(QCoreApplication.translate('PreferencesDialog', 'From Address', None))
self.smtpPortLabel.setText(QCoreApplication.translate('PreferencesDialog', 'SMTP Server Port', None))
self.useSTARTTLS.setText(QCoreApplication.translate('PreferencesDialog', 'STARTTLS', None))
self.noSecurity.setText(QCoreApplication.translate('PreferencesDialog', 'No Security', None))
self.useAuthentication.setText(QCoreApplication.translate('PreferencesDialog', 'Use Authentication', None))
self.testEmail.setText(QCoreApplication.translate('PreferencesDialog', 'Send Test Email', None))
self.enableAlertEmail.setText(QCoreApplication.translate('PreferencesDialog', 'Send email when alert is generated', None))
self.tabWidget.setTabText(self.tabWidget.indexOf(self.alertTab), QCoreApplication.translate('PreferencesDialog', 'Alerts', None))
