# Source Generated with Decompyle++
# File: tmp37aw9tu3.marshal (Python 3.11)

MondoMainWindow.setWindowTitle(QCoreApplication.translate('MondoMainWindow', 'Mondo', None))
self.actionAbout.setText(QCoreApplication.translate('MondoMainWindow', 'About Mondo...', None))
self.actionAbout.setToolTip(QCoreApplication.translate('MondoMainWindow', 'About Mondo...', None))
self.actionExit.setText(QCoreApplication.translate('MondoMainWindow', 'Exit', None))
self.actionAboutLibraries.setText(QCoreApplication.translate('MondoMainWindow', 'About Libraries...', None))
self.actionAboutLibraries.setToolTip(QCoreApplication.translate('MondoMainWindow', 'About Libraries...', None))
self.actionUpdateLatestStable.setText(QCoreApplication.translate('MondoMainWindow', 'Latest Stable', None))
self.actionUpdateSpecificBranch.setText(QCoreApplication.translate('MondoMainWindow', 'Specific Branch...', None))
self.actionUpdateSpecificCommit.setText(QCoreApplication.translate('MondoMainWindow', 'Specific Commit..', None))
self.actionUpdateCurrentBranch.setText(QCoreApplication.translate('MondoMainWindow', 'Latest branch', None))
self.actionPreferences.setText(QCoreApplication.translate('MondoMainWindow', 'Preferences...', None))
self.actionPreferences.setToolTip(QCoreApplication.translate('MondoMainWindow', 'Preferences...', None))
self.actionShowLogs.setText(QCoreApplication.translate('MondoMainWindow', 'Show Logs on Disk...', None))
self.groupBox.setTitle(QCoreApplication.translate('MondoMainWindow', 'Frequency Analysis', None))
self.psdButton.setText(QCoreApplication.translate('MondoMainWindow', 'Power Spectral Density (PSD)', None))
self.singleChannelPsdButton.setToolTip(QCoreApplication.translate('MondoMainWindow', 'Overlaid PSD streamlined for plotting a single channel across multiple time slices', None))
self.singleChannelPsdButton.setText(QCoreApplication.translate('MondoMainWindow', 'Single Channel Overlaid PSD', None))
self.singleSlicePsdButton.setToolTip(QCoreApplication.translate('MondoMainWindow', 'Overlaid PSD streamlined for plotting multiple channels in a single time slice', None))
self.singleSlicePsdButton.setText(QCoreApplication.translate('MondoMainWindow', 'Single Time Slice Overlaid PSD', None))
self.overlaidPsdButton.setToolTip(QCoreApplication.translate('MondoMainWindow', 'Ovelaid PSD for plotting arbitrary channels and time slices ', None))
self.overlaidPsdButton.setText(QCoreApplication.translate('MondoMainWindow', 'Overlaid PSD', None))
self.groupBox_4.setTitle(QCoreApplication.translate('MondoMainWindow', 'Raw Data', None))
self.csvButton.setText(QCoreApplication.translate('MondoMainWindow', 'CSV Output', None))
self.csvDownsampledButton.setText(QCoreApplication.translate('MondoMainWindow', 'CSV Downsampled Output', None))
self.groupBox_2.setTitle(QCoreApplication.translate('MondoMainWindow', 'Time/Frequency Analysis', None))
self.spectrogramButton.setText(QCoreApplication.translate('MondoMainWindow', 'Spectrogram', None))
self.groupBox_3.setTitle(QCoreApplication.translate('MondoMainWindow', 'Time Analysis', None))
self.timeButton.setText(QCoreApplication.translate('MondoMainWindow', 'Time Data', None))
self.synchronousTimeButton.setText(QCoreApplication.translate('MondoMainWindow', 'Synchronous Time Data', None))
self.overlaidTimeButton.setText(QCoreApplication.translate('MondoMainWindow', 'Overlaid Time Data', None))
self.groupBox_5.setTitle(QCoreApplication.translate('MondoMainWindow', 'File Manipulation', None))
self.fileInformationButton.setText(QCoreApplication.translate('MondoMainWindow', 'Device Information', None))
self.viewSettingsButton.setText(QCoreApplication.translate('MondoMainWindow', 'View Device Settings', None))
self.rawExportButton.setText(QCoreApplication.translate('MondoMainWindow', 'Advanced Raw Export', None))
self.splitFileButton.setText(QCoreApplication.translate('MondoMainWindow', 'Split File', None))
self.menuFile.setTitle(QCoreApplication.translate('MondoMainWindow', 'File', None))
self.menuHelp.setTitle(QCoreApplication.translate('MondoMainWindow', 'Help', None))
self.menuCheckForUpdates.setTitle(QCoreApplication.translate('MondoMainWindow', 'Check for Updates', None))
self.menuSettings.setTitle(QCoreApplication.translate('MondoMainWindow', 'Settings', None))
