# Source Generated with Decompyle++
# File: tmpgb_c0yb7.marshal (Python 3.11)


def setupUi(self, MondoMainWindow):
    if not MondoMainWindow.objectName():
        MondoMainWindow.setObjectName('MondoMainWindow')
    MondoMainWindow.resize(617, 366)
    self.actionAbout = QAction(MondoMainWindow)
    self.actionAbout.setObjectName('actionAbout')
    self.actionExit = QAction(MondoMainWindow)
    self.actionExit.setObjectName('actionExit')
    self.actionAboutLibraries = QAction(MondoMainWindow)
    self.actionAboutLibraries.setObjectName('actionAboutLibraries')
    self.actionUpdateLatestStable = QAction(MondoMainWindow)
    self.actionUpdateLatestStable.setObjectName('actionUpdateLatestStable')
    self.actionUpdateSpecificBranch = QAction(MondoMainWindow)
    self.actionUpdateSpecificBranch.setObjectName('actionUpdateSpecificBranch')
    self.actionUpdateSpecificCommit = QAction(MondoMainWindow)
    self.actionUpdateSpecificCommit.setObjectName('actionUpdateSpecificCommit')
    self.actionUpdateCurrentBranch = QAction(MondoMainWindow)
    self.actionUpdateCurrentBranch.setObjectName('actionUpdateCurrentBranch')
    self.actionPreferences = QAction(MondoMainWindow)
    self.actionPreferences.setObjectName('actionPreferences')
    self.actionShowLogs = QAction(MondoMainWindow)
    self.actionShowLogs.setObjectName('actionShowLogs')
    self.centralwidget = QWidget(MondoMainWindow)
    self.centralwidget.setObjectName('centralwidget')
    self.verticalLayout_5 = QVBoxLayout(self.centralwidget)
    self.verticalLayout_5.setObjectName('verticalLayout_5')
    self.gridLayout = QGridLayout()
    self.gridLayout.setObjectName('gridLayout')
    self.groupBox = QGroupBox(self.centralwidget)
    self.groupBox.setObjectName('groupBox')
    self.verticalLayout = QVBoxLayout(self.groupBox)
    self.verticalLayout.setObjectName('verticalLayout')
    self.psdButton = QPushButton(self.groupBox)
    self.psdButton.setObjectName('psdButton')
    self.psdButton.setMinimumSize(QSize(175, 0))
    self.verticalLayout.addWidget(self.psdButton)
    self.singleChannelPsdButton = QPushButton(self.groupBox)
    self.singleChannelPsdButton.setObjectName('singleChannelPsdButton')
    self.verticalLayout.addWidget(self.singleChannelPsdButton)
    self.singleSlicePsdButton = QPushButton(self.groupBox)
    self.singleSlicePsdButton.setObjectName('singleSlicePsdButton')
    self.verticalLayout.addWidget(self.singleSlicePsdButton)
    self.overlaidPsdButton = QPushButton(self.groupBox)
    self.overlaidPsdButton.setObjectName('overlaidPsdButton')
    self.overlaidPsdButton.setMinimumSize(QSize(175, 0))
    self.verticalLayout.addWidget(self.overlaidPsdButton)
    self.verticalSpacer = QSpacerItem(20, 0, QSizePolicy.Minimum, QSizePolicy.Expanding)
    self.verticalLayout.addItem(self.verticalSpacer)
    self.gridLayout.addWidget(self.groupBox, 0, 2, 1, 1)
    self.groupBox_4 = QGroupBox(self.centralwidget)
    self.groupBox_4.setObjectName('groupBox_4')
    self.verticalLayout_4 = QVBoxLayout(self.groupBox_4)
    self.verticalLayout_4.setObjectName('verticalLayout_4')
    self.csvButton = QPushButton(self.groupBox_4)
    self.csvButton.setObjectName('csvButton')
    self.csvButton.setMinimumSize(QSize(175, 0))
    self.verticalLayout_4.addWidget(self.csvButton)
    self.csvDownsampledButton = QPushButton(self.groupBox_4)
    self.csvDownsampledButton.setObjectName('csvDownsampledButton')
    self.csvDownsampledButton.setMinimumSize(QSize(175, 0))
    self.verticalLayout_4.addWidget(self.csvDownsampledButton)
    self.verticalSpacer_4 = QSpacerItem(20, 0, QSizePolicy.Minimum, QSizePolicy.Expanding)
    self.verticalLayout_4.addItem(self.verticalSpacer_4)
    self.gridLayout.addWidget(self.groupBox_4, 1, 0, 1, 1)
    self.groupBox_2 = QGroupBox(self.centralwidget)
    self.groupBox_2.setObjectName('groupBox_2')
    self.verticalLayout_2 = QVBoxLayout(self.groupBox_2)
    self.verticalLayout_2.setObjectName('verticalLayout_2')
    self.spectrogramButton = QPushButton(self.groupBox_2)
    self.spectrogramButton.setObjectName('spectrogramButton')
    self.spectrogramButton.setMinimumSize(QSize(175, 0))
    self.verticalLayout_2.addWidget(self.spectrogramButton)
    self.verticalSpacer_2 = QSpacerItem(20, 0, QSizePolicy.Minimum, QSizePolicy.Expanding)
    self.verticalLayout_2.addItem(self.verticalSpacer_2)
    self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
    self.groupBox_3 = QGroupBox(self.centralwidget)
    self.groupBox_3.setObjectName('groupBox_3')
    self.verticalLayout_3 = QVBoxLayout(self.groupBox_3)
    self.verticalLayout_3.setObjectName('verticalLayout_3')
    self.timeButton = QPushButton(self.groupBox_3)
    self.timeButton.setObjectName('timeButton')
    self.timeButton.setMinimumSize(QSize(175, 0))
    self.verticalLayout_3.addWidget(self.timeButton)
    self.synchronousTimeButton = QPushButton(self.groupBox_3)
    self.synchronousTimeButton.setObjectName('synchronousTimeButton')
    self.synchronousTimeButton.setMinimumSize(QSize(175, 0))
    self.verticalLayout_3.addWidget(self.synchronousTimeButton)
    self.overlaidTimeButton = QPushButton(self.groupBox_3)
    self.overlaidTimeButton.setObjectName('overlaidTimeButton')
    self.overlaidTimeButton.setMinimumSize(QSize(175, 0))
    self.verticalLayout_3.addWidget(self.overlaidTimeButton)
    self.verticalSpacer_3 = QSpacerItem(20, 0, QSizePolicy.Minimum, QSizePolicy.Expanding)
    self.verticalLayout_3.addItem(self.verticalSpacer_3)
    self.gridLayout.addWidget(self.groupBox_3, 0, 0, 1, 1)
    self.groupBox_5 = QGroupBox(self.centralwidget)
    self.groupBox_5.setObjectName('groupBox_5')
    self.verticalLayout_6 = QVBoxLayout(self.groupBox_5)
    self.verticalLayout_6.setObjectName('verticalLayout_6')
    self.fileInformationButton = QPushButton(self.groupBox_5)
    self.fileInformationButton.setObjectName('fileInformationButton')
    self.verticalLayout_6.addWidget(self.fileInformationButton)
    self.viewSettingsButton = QPushButton(self.groupBox_5)
    self.viewSettingsButton.setObjectName('viewSettingsButton')
    self.verticalLayout_6.addWidget(self.viewSettingsButton)
    self.rawExportButton = QPushButton(self.groupBox_5)
    self.rawExportButton.setObjectName('rawExportButton')
    self.verticalLayout_6.addWidget(self.rawExportButton)
    self.splitFileButton = QPushButton(self.groupBox_5)
    self.splitFileButton.setObjectName('splitFileButton')
    self.verticalLayout_6.addWidget(self.splitFileButton)
    self.verticalSpacer_6 = QSpacerItem(20, 0, QSizePolicy.Minimum, QSizePolicy.Expanding)
    self.verticalLayout_6.addItem(self.verticalSpacer_6)
    self.gridLayout.addWidget(self.groupBox_5, 1, 1, 1, 1)
    self.verticalLayout_5.addLayout(self.gridLayout)
    self.verticalSpacer_5 = QSpacerItem(20, 0, QSizePolicy.Minimum, QSizePolicy.Expanding)
    self.verticalLayout_5.addItem(self.verticalSpacer_5)
    self.verticalLayout_5.setStretch(1, 1)
    MondoMainWindow.setCentralWidget(self.centralwidget)
    self.menubar = QMenuBar(MondoMainWindow)
    self.menubar.setObjectName('menubar')
    self.menubar.setGeometry(QRect(0, 0, 617, 22))
    self.menuFile = QMenu(self.menubar)
    self.menuFile.setObjectName('menuFile')
    self.menuHelp = QMenu(self.menubar)
    self.menuHelp.setObjectName('menuHelp')
    self.menuCheckForUpdates = QMenu(self.menuHelp)
    self.menuCheckForUpdates.setObjectName('menuCheckForUpdates')
    self.menuSettings = QMenu(self.menubar)
    self.menuSettings.setObjectName('menuSettings')
    MondoMainWindow.setMenuBar(self.menubar)
    self.menubar.addAction(self.menuFile.menuAction())
    self.menubar.addAction(self.menuSettings.menuAction())
    self.menubar.addAction(self.menuHelp.menuAction())
    self.menuFile.addAction(self.actionExit)
    self.menuHelp.addAction(self.menuCheckForUpdates.menuAction())
    self.menuHelp.addSeparator()
    self.menuHelp.addAction(self.actionShowLogs)
    self.menuHelp.addSeparator()
    self.menuHelp.addAction(self.actionAbout)
    self.menuHelp.addAction(self.actionAboutLibraries)
    self.menuCheckForUpdates.addAction(self.actionUpdateLatestStable)
    self.menuCheckForUpdates.addAction(self.actionUpdateCurrentBranch)
    self.menuCheckForUpdates.addAction(self.actionUpdateSpecificBranch)
    self.menuCheckForUpdates.addAction(self.actionUpdateSpecificCommit)
    self.menuSettings.addAction(self.actionPreferences)
    self.retranslateUi(MondoMainWindow)
    self.actionExit.triggered.connect(MondoMainWindow.close)
    QMetaObject.connectSlotsByName(MondoMainWindow)


def retranslateUi(self, MondoMainWindow):
    MondoMainWindow.setWindowTitle(QCoreApplication.translate('MondoMainWindow', 'Mondo', None))
    self.actionAbout.setText(QCoreApplication.translate('MondoMainWindow', 'About Mondo...', None))
    self.actionAbout.setToolTip(QCoreApplication.translate('MondoMainWindow', 'About Mondo...', None))
    self.actionExit.setText(QCoreApplication.translate('MondoMainWindow', 'Exit', None))
    self.actionAboutLibraries.setText(QCoreApplication.translate('MondoMainWindow', 'About Libraries...', None))
    self.actionAboutLibraries.setToolTip(QCoreApplication.translate('MondoMainWindow', 'About Libraries...', None))
    self.actionUpdateLatestStable.setText(QCoreApplication.translate('MondoMainWindow', 'Latest Stable', None))
    self.actionUpdateSpecificBranch.setText(QCoreApplication.translate('MondoMainWindow', 'Specific Branch...', None))
    self.actionUpdateSpecificCommit.setText(QCoreApplication.translate('MondoMainWindow', 'Specific Commit..', None))
    self.actionUpdateCurrentBranch.setText(QCoreApplication.translate('MondoMainWindow', 'Latest branch', None))
    self.actionPreferences.setText(QCoreApplication.translate('MondoMainWindow', 'Preferences...', None))
    self.actionPreferences.setToolTip(QCoreApplication.translate('MondoMainWindow', 'Preferences...', None))
    self.actionShowLogs.setText(QCoreApplication.translate('MondoMainWindow', 'Show Logs on Disk...', None))
    self.groupBox.setTitle(QCoreApplication.translate('MondoMainWindow', 'Frequency Analysis', None))
    self.psdButton.setText(QCoreApplication.translate('MondoMainWindow', 'Power Spectral Density (PSD)', None))
    self.singleChannelPsdButton.setToolTip(QCoreApplication.translate('MondoMainWindow', 'Overlaid PSD streamlined for plotting a single channel across multiple time slices', None))
    self.singleChannelPsdButton.setText(QCoreApplication.translate('MondoMainWindow', 'Single Channel Overlaid PSD', None))
    self.singleSlicePsdButton.setToolTip(QCoreApplication.translate('MondoMainWindow', 'Overlaid PSD streamlined for plotting multiple channels in a single time slice', None))
    self.singleSlicePsdButton.setText(QCoreApplication.translate('MondoMainWindow', 'Single Time Slice Overlaid PSD', None))
    self.overlaidPsdButton.setToolTip(QCoreApplication.translate('MondoMainWindow', 'Ovelaid PSD for plotting arbitrary channels and time slices ', None))
    self.overlaidPsdButton.setText(QCoreApplication.translate('MondoMainWindow', 'Overlaid PSD', None))
    self.groupBox_4.setTitle(QCoreApplication.translate('MondoMainWindow', 'Raw Data', None))
    self.csvButton.setText(QCoreApplication.translate('MondoMainWindow', 'CSV Output', None))
    self.csvDownsampledButton.setText(QCoreApplication.translate('MondoMainWindow', 'CSV Downsampled Output', None))
    self.groupBox_2.setTitle(QCoreApplication.translate('MondoMainWindow', 'Time/Frequency Analysis', None))
    self.spectrogramButton.setText(QCoreApplication.translate('MondoMainWindow', 'Spectrogram', None))
    self.groupBox_3.setTitle(QCoreApplication.translate('MondoMainWindow', 'Time Analysis', None))
    self.timeButton.setText(QCoreApplication.translate('MondoMainWindow', 'Time Data', None))
    self.synchronousTimeButton.setText(QCoreApplication.translate('MondoMainWindow', 'Synchronous Time Data', None))
    self.overlaidTimeButton.setText(QCoreApplication.translate('MondoMainWindow', 'Overlaid Time Data', None))
    self.groupBox_5.setTitle(QCoreApplication.translate('MondoMainWindow', 'File Manipulation', None))
    self.fileInformationButton.setText(QCoreApplication.translate('MondoMainWindow', 'Device Information', None))
    self.viewSettingsButton.setText(QCoreApplication.translate('MondoMainWindow', 'View Device Settings', None))
    self.rawExportButton.setText(QCoreApplication.translate('MondoMainWindow', 'Advanced Raw Export', None))
    self.splitFileButton.setText(QCoreApplication.translate('MondoMainWindow', 'Split File', None))
    self.menuFile.setTitle(QCoreApplication.translate('MondoMainWindow', 'File', None))
    self.menuHelp.setTitle(QCoreApplication.translate('MondoMainWindow', 'Help', None))
    self.menuCheckForUpdates.setTitle(QCoreApplication.translate('MondoMainWindow', 'Check for Updates', None))
    self.menuSettings.setTitle(QCoreApplication.translate('MondoMainWindow', 'Settings', None))

