# Source Generated with Decompyle++
# File: tmplxal3q3v.marshal (Python 3.11)

TCPScanDialog.setWindowTitle(QCoreApplication.translate('TCPScanDialog', 'TCP Devices', None))
_Ui_TCPScanDialog___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
_Ui_TCPScanDialog___qtablewidgetitem.setText(QCoreApplication.translate('TCPScanDialog', 'Serial', None))
_Ui_TCPScanDialog___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
_Ui_TCPScanDialog___qtablewidgetitem1.setText(QCoreApplication.translate('TCPScanDialog', 'Tag 1', None))
_Ui_TCPScanDialog___qtablewidgetitem2 = self.tableWidget.horizontalHeaderItem(2)
_Ui_TCPScanDialog___qtablewidgetitem2.setText(QCoreApplication.translate('TCPScanDialog', 'Tag 2', None))
_Ui_TCPScanDialog___qtablewidgetitem3 = self.tableWidget.horizontalHeaderItem(3)
_Ui_TCPScanDialog___qtablewidgetitem3.setText(QCoreApplication.translate('TCPScanDialog', 'Board Info', None))
_Ui_TCPScanDialog___qtablewidgetitem4 = self.tableWidget.horizontalHeaderItem(4)
_Ui_TCPScanDialog___qtablewidgetitem4.setText(QCoreApplication.translate('TCPScanDialog', 'Build Info', None))
_Ui_TCPScanDialog___qtablewidgetitem5 = self.tableWidget.horizontalHeaderItem(5)
_Ui_TCPScanDialog___qtablewidgetitem5.setText(QCoreApplication.translate('TCPScanDialog', 'Build Date', None))
_Ui_TCPScanDialog___qtablewidgetitem6 = self.tableWidget.horizontalHeaderItem(6)
_Ui_TCPScanDialog___qtablewidgetitem6.setText(QCoreApplication.translate('TCPScanDialog', 'Bootloader', None))
_Ui_TCPScanDialog___qtablewidgetitem7 = self.tableWidget.horizontalHeaderItem(7)
_Ui_TCPScanDialog___qtablewidgetitem7.setText(QCoreApplication.translate('TCPScanDialog', 'Available', None))
self.automaticRescan.setText(QCoreApplication.translate('TCPScanDialog', 'Automatic Rescan', None))
