# Source Generated with Decompyle++
# File: tmp39l7rc5g.marshal (Python 3.11)

self.calibrationEnabled.toggled.connect(self.update_all)
self.tabWidget.setCurrentIndex(0)
self.tabWidget.currentChanged.connect(self.update_all)
self.selectUnit.clicked.connect(self.select_unit)
self.unit.setText('')
self.acCapture.clicked.connect(self.ac_capture)
self.linearCapture.clicked.connect(self.linear_capture)
self.plotButton.clicked.connect(self.plot_linear)
self.capturedMagnitude.set_unit_formatter(self.rms_formatter)
self.capturedOffset.set_unit_formatter(self.dc_formatter)
self.capturedMagnitude.setMinimum(-(math.inf))
self.capturedMagnitude.setMaximum(math.inf)
self.capturedOffset.setMinimum(-(math.inf))
self.capturedOffset.setMaximum(math.inf)
self.actualMagnitude.setMinimum(-(math.inf))
self.actualMagnitude.setMaximum(math.inf)
self.actualOffset.setMinimum(-(math.inf))
self.actualOffset.setMaximum(math.inf)
self.capturedMagnitude.valueChanged.connect(self.update_scale_offset)
self.capturedOffset.valueChanged.connect(self.update_scale_offset)
self.actualMagnitude.valueChanged.connect(self.update_scale_offset)
self.actualOffset.valueChanged.connect(self.update_scale_offset)
header = self.linearTable.horizontalHeader()
header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeMode.Stretch)
header.setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeMode.Stretch)
header.setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeMode.ResizeToContents)
