# Source Generated with Decompyle++
# File: tmp60n6w9w6.marshal (Python 3.11)

self.log_list_model = get_log_list_model(self.controller.serial_number)
self.log_list_model.dataChanged.connect(self.log_list_updated)
self.logList.setModel(self.log_list_model)
self.logListDisconnected.setModel(self.log_list_model)
self.log_selection_model = QtCore.QItemSelectionModel(self.log_list_model)
self.logList.setSelectionModel(self.log_selection_model)
self.logListDisconnected.setSelectionModel(self.log_selection_model)
self.logListDisconnected.setVisible(False)
self.logList.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
self.logListDisconnected.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
self.copy_log_action = QtGui.QAction()
self.copy_log_action.setText(self.tr('Copy'))
self.copy_log_action.setShortcut(QtGui.QKeySequence.StandardKey.Copy)
self.copy_log_action.setShortcutContext(QtCore.Qt.ShortcutContext.WidgetShortcut)
self.copy_log_action.triggered.connect(self._copy_log_cb)
self.logList.addAction(self.copy_log_action)
self.logListDisconnected.addAction(self.copy_log_action)
sb1 = self.logList.verticalScrollBar()
sb2 = self.logListDisconnected.verticalScrollBar()
sb1.valueChanged.connect(sb2.setValue)
sb2.valueChanged.connect(sb1.setValue)
