# Source Generated with Decompyle++
# File: tmpjqythuve.marshal (Python 3.11)

self.actionCalibrate.setEnabled(False)
self.actionChangeActiveStreams.setEnabled(False)
self.actionEditDeviceSettings.setEnabled(False)
self.actionFirmwareFromBranch.setEnabled(False)
self.actionFirmwareFromCommit.setEnabled(False)
self.actionFirmwareFromFile.setEnabled(False)
self.actionFirmwareLatestStable.setEnabled(False)
self.actionForceReset.setEnabled(False)
self.actionForceRunApplication.setEnabled(False)
self.actionForceRunBootloader.setEnabled(False)
self.actionRaiseException.setEnabled(False)
self.actionRecoverNVM.setEnabled(False)
self.actionRFTest.setEnabled(False)
self.actionRunTests.setEnabled(False)
self.actionSetDeviceMode.setEnabled(False)
self.actionSetUserTag1.setEnabled(False)
self.actionSetUserTag2.setEnabled(False)
self.actionShakerCalibrate.setEnabled(False)
if self.calibration_panel:
    self.calibration_panel.setEnabled(False)
self.firmware_menu.setEnabled(False)
self.menuButton.setEnabled(False)
self.radio_panel.setEnabled(False)
