# Source Generated with Decompyle++
# File: tmpaqwcu754.marshal (Python 3.11)

self.stackedWidget.setCurrentIndex(0)
self.statusProgressBar.setVisible(False)
self.serialNumber.setText(self.controller.serial_number)
self.userTag1.setText('')
self.userTag2.setText('')
self.boardInfo.setText('')
self.buildInfo.setText('')
self.buildDate.setText('')
self.branch.setText('')
self.bootloaderIndicator.setVisible(False)
self.nvmModifiedIndicator.setVisible(False)
self.schedule_or_trigger_count_updated()
self.menu = QtWidgets.QMenu()
self.firmware_menu = self.menu.addMenu(self.tr('Update Firmware'))
self.firmware_menu.setEnabled(False)
self.firmware_menu.addAction(self.actionFirmwareLatestStable)
self.firmware_menu.addAction(self.actionFirmwareFromBranch)
self.firmware_menu.addAction(self.actionFirmwareFromCommit)
self.firmware_menu.addAction(self.actionFirmwareFromFile)
self.advanced_menu = self.menu.addMenu(self.tr('Advanced Actions'))
self.advanced_menu.addAction(self.actionForceRunBootloader)
self.advanced_menu.addAction(self.actionForceRunApplication)
self.advanced_menu.addAction(self.actionForceReset)
self.advanced_menu.addAction(self.actionRaiseException)
self.advanced_menu.addAction(self.actionRecoverNVM)
self.menu.addSeparator()
self.menu.addAction(self.actionCalibrate)
self.menu.addAction(self.actionShakerCalibrate)
self.menu.addSeparator()
self.menu.addAction(self.actionConnectivity)
self.actionRFTestSeparator = self.menu.addSeparator()
self.menu.addAction(self.actionRFTest)
self.menu.addSeparator()
self.menu.addAction(self.actionSetDeviceMode)
self.menu.addAction(self.actionChangeActiveStreams)
self.menu.addAction(self.actionRunTests)
self.menuButton.setMenu(self.menu)
self.actionCalibrate.setIcon(QtGui.QIcon.fromTheme('caliper'))
self.actionChangeActiveStreams.setIcon(QtGui.QIcon.fromTheme('preferences_edit'))
self.actionConnectivity.setIcon(QtGui.QIcon.fromTheme('client_network'))
self.actionEditDeviceSettings.setIcon(QtGui.QIcon.fromTheme('gear'))
self.actionFirmwareFromBranch.setIcon(QtGui.QIcon.fromTheme('branch_view'))
self.actionFirmwareFromCommit.setIcon(QtGui.QIcon.fromTheme('symbol_hash'))
self.actionFirmwareFromFile.setIcon(QtGui.QIcon.fromTheme('document_plain'))
self.actionFirmwareLatestStable.setIcon(QtGui.QIcon.fromTheme('branch'))
self.actionForceReset.setIcon(QtGui.QIcon.fromTheme('redo'))
self.actionForceRunApplication.setIcon(QtGui.QIcon.fromTheme('application'))
self.actionForceRunBootloader.setIcon(QtGui.QIcon.fromTheme('flash_yellow'))
self.actionRaiseException.setIcon(QtGui.QIcon.fromTheme('bomb'))
self.actionRecoverNVM.setIcon(QtGui.QIcon.fromTheme('document_gear'))
self.actionRFTest.setIcon(QtGui.QIcon.fromTheme('rf_test'))
self.actionRunTests.setIcon(QtGui.QIcon.fromTheme('stethoscope'))
self.actionSetDeviceMode.setIcon(QtGui.QIcon.fromTheme('text_list_numbers'))
self.actionCopySerialNumber.setIcon(QtGui.QIcon.fromTheme('copy'))
self.actionSetUserTag1.setIcon(QtGui.QIcon.fromTheme('tag'))
self.actionSetUserTag2.setIcon(QtGui.QIcon.fromTheme('tag'))
self.actionShakerCalibrate.setIcon(QtGui.QIcon.fromTheme('shaker'))
self.actionShowDeviceInfo.setIcon(QtGui.QIcon.fromTheme('information'))
self.actionFlushLostPackets.setIcon(QtGui.QIcon.fromTheme('replace2'))
self.actionShowPacketStats.setIcon(QtGui.QIcon.fromTheme('chart_column'))
self.firmware_menu.setIcon(QtGui.QIcon.fromTheme('cpu_flash'))
self.advanced_menu.setIcon(QtGui.QIcon.fromTheme('wrench'))
self.firmware_progress = QtWidgets.QProgressDialog('', '', 0, 100)
self.firmware_progress.setLabelText(self.tr(''))
self.firmware_progress.setWindowTitle(self.tr('Firmware Update'))
self.firmware_progress.setCancelButton(None)
self.firmware_progress.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
self.firmware_progress.setMinimumDuration(0)
self.firmware_progress.setAutoReset(False)
self.firmware_progress.reset()
self.set_collapsed(self.collapsed)
self.deviceInfo.setDefaultAction(self.actionShowDeviceInfo)
self.copySerialNumber.setDefaultAction(self.actionCopySerialNumber)
self.setUserTag1.setDefaultAction(self.actionSetUserTag1)
self.setUserTag2.setDefaultAction(self.actionSetUserTag2)
self.flushLostPackets.setDefaultAction(self.actionFlushLostPackets)
self.lostPacketDetails.setDefaultAction(self.actionShowPacketStats)
self.editDeviceSettings.setDefaultAction(self.actionEditDeviceSettings)
self.ctrl_var_panel = CtrlVarPanel(self)
self.panelLayout.addWidget(self.ctrl_var_panel)
self.rf_power_panel = RFPowerPanel(self.controller, self)
self.panelLayout.addWidget(self.rf_power_panel)
self.radio_panel = RadioPanel(self.controller, self.plotmain.dispatcher.active_scan_database, self.preferences, self)
self.radio_panel.show_remote_clicked.connect(self.show_remote_tab)
self.panelLayout.addWidget(self.radio_panel)
self.remote_panel = RemotePanel(self)
self.remote_panel.show_radio_clicked.connect(self.show_radio_tab)
self.panelLayout.addWidget(self.remote_panel)
inactive_triggers = self.controller.trigger_names.difference(self.controller.last_emitted_active_triggers)
self.active_triggers_changed_cb(self.controller, self.controller.last_emitted_active_triggers, inactive_triggers)
