# Source Generated with Decompyle++
# File: tmplftkd_pb.marshal (Python 3.11)

self.closeButton.clicked.connect(self.close_controller)
self.graphChannelComboBox.currentIndexChanged.connect(self.graph_channel_changed)
self.fftSubchannelComboBox.currentIndexChanged.connect(self.fft_subchannel_changed)
self.actionCopySerialNumber.triggered.connect(self.copy_serial_number)
self.actionSetUserTag1.triggered.connect(self.set_user_tag_1)
self.actionSetUserTag2.triggered.connect(self.set_user_tag_2)
self.actionFirmwareLatestStable.triggered.connect(self.do_bootloader_latest_stable)
self.actionFirmwareFromBranch.triggered.connect(self.do_bootloader_from_branch)
self.actionFirmwareFromCommit.triggered.connect(self.do_bootloader_from_commit)
self.actionFirmwareFromFile.triggered.connect(self.do_bootloader_from_file)
self.actionForceRunBootloader.triggered.connect(self.controller.force_run_bootloader)
self.actionForceRunApplication.triggered.connect(self.controller.force_run_application)
self.actionForceReset.triggered.connect(self.controller.force_reset)
self.actionRaiseException.triggered.connect(self.controller.do_explode)
self.actionRecoverNVM.triggered.connect(self.recover_nvm)
self.actionFlushLostPackets.triggered.connect(self.flush_lost_packets)
self.actionShowPacketStats.triggered.connect(self.show_packet_stats)
self.actionChangeActiveStreams.triggered.connect(self.change_active_streams)
self.actionShowDeviceInfo.triggered.connect(self.show_device_info)
self.actionCalibrate.triggered.connect(self.calibrate)
self.actionShakerCalibrate.triggered.connect(self.shaker_calibrate)
self.actionConnectivity.triggered.connect(self.show_connectivity_dialog)
self.actionRFTest.triggered.connect(self.rf_test)
self.actionEditDeviceSettings.triggered.connect(self.edit_settings)
self.actionRunTests.triggered.connect(self.run_tests)
self.actionSetDeviceMode.triggered.connect(self.set_device_mode)
self.collapseButton.clicked.connect(self.toggle_collapsed)
self.controller.state_changed_signal.connect(self.controller_state_changed)
self.controller.progress_signal.connect(self.progress_update)
self.controller.channel_update.connect(self.channel_update_cb)
self.controller.plot_update.connect(self.plot_update_cb)
self.controller.fft_update.connect(self.fft_update_cb)
self.controller.lost_packet_update.connect(self.lost_packet_update)
self.controller.rgb_updated.connect(self.rgb_updated_cb)
self.controller.led_updated.connect(self.led_updated_cb)
self.controller.ctrl_var_updated.connect(self.ctrl_var_updated_cb)
self.controller.alerts_changed.connect(self.alerts_changed_cb)
self.controller.manual_control_changed.connect(self._manual_control_changed_cb)
self.controller.trigger_count_changed.connect(self.schedule_or_trigger_count_updated)
self.controller.schedule_count_changed.connect(self.schedule_or_trigger_count_updated)
self.controller.active_triggers_changed.connect(self.active_triggers_changed_cb)
self.firmware_finder = hyperborea.download.FirmwareFinder(self.logger)
self.firmware_finder.completed.connect(self.firmware_finder_completed)
self.firmware_finder.error.connect(self.firmware_finder_error)
self.ref_finder = hyperborea.download.RefFinder(self.logger)
self.ref_finder.completed.connect(self.ref_finder_completed)
self.ref_finder.error.connect(self.ref_finder_error)
self.downloader = hyperborea.download.Downloader(self.logger)
self.downloader.completed.connect(self.download_completed)
self.downloader.error.connect(self.download_error)
self.downloader.update.connect(self.download_update_progress)
