# Source Generated with Decompyle++
# File: tmpi791j335.marshal (Python 3.11)


def setupUi(self, AboutDialog):
    if not AboutDialog.objectName():
        AboutDialog.setObjectName('AboutDialog')
    AboutDialog.resize(505, 506)
    self.verticalLayout = QVBoxLayout(AboutDialog)
    self.verticalLayout.setObjectName('verticalLayout')
    self.formLayout = QFormLayout()
    self.formLayout.setObjectName('formLayout')
    self.formLayout.setFieldGrowthPolicy(QFormLayout.AllNonFixedFieldsGrow)
    self.formLayout.setVerticalSpacing(20)
    self.label = QLabel(AboutDialog)
    self.label.setObjectName('label')
    self.formLayout.setWidget(0, QFormLayout.LabelRole, self.label)
    self.softwareLabel = QLabel(AboutDialog)
    self.softwareLabel.setObjectName('softwareLabel')
    sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.softwareLabel.sizePolicy().hasHeightForWidth())
    self.softwareLabel.setSizePolicy(sizePolicy)
    self.formLayout.setWidget(0, QFormLayout.FieldRole, self.softwareLabel)
    self.label_4 = QLabel(AboutDialog)
    self.label_4.setObjectName('label_4')
    self.formLayout.setWidget(1, QFormLayout.LabelRole, self.label_4)
    self.label_9 = QLabel(AboutDialog)
    self.label_9.setObjectName('label_9')
    sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.MinimumExpanding)
    sizePolicy1.setHorizontalStretch(0)
    sizePolicy1.setVerticalStretch(0)
    sizePolicy1.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
    self.label_9.setSizePolicy(sizePolicy1)
    self.label_9.setWordWrap(True)
    self.formLayout.setWidget(1, QFormLayout.FieldRole, self.label_9)
    self.label_5 = QLabel(AboutDialog)
    self.label_5.setObjectName('label_5')
    self.formLayout.setWidget(2, QFormLayout.LabelRole, self.label_5)
    self.label_10 = QLabel(AboutDialog)
    self.label_10.setObjectName('label_10')
    sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
    self.label_10.setSizePolicy(sizePolicy)
    self.label_10.setWordWrap(True)
    self.formLayout.setWidget(2, QFormLayout.FieldRole, self.label_10)
    self.label_6 = QLabel(AboutDialog)
    self.label_6.setObjectName('label_6')
    self.formLayout.setWidget(3, QFormLayout.LabelRole, self.label_6)
    self.label_11 = QLabel(AboutDialog)
    self.label_11.setObjectName('label_11')
    sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
    self.label_11.setSizePolicy(sizePolicy)
    self.label_11.setWordWrap(True)
    self.formLayout.setWidget(3, QFormLayout.FieldRole, self.label_11)
    self.label_7 = QLabel(AboutDialog)
    self.label_7.setObjectName('label_7')
    self.formLayout.setWidget(4, QFormLayout.LabelRole, self.label_7)
    self.label_12 = QLabel(AboutDialog)
    self.label_12.setObjectName('label_12')
    sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
    self.label_12.setSizePolicy(sizePolicy)
    font = QFont()
    font.setBold(True)
    self.label_12.setFont(font)
    self.label_12.setWordWrap(True)
    self.formLayout.setWidget(4, QFormLayout.FieldRole, self.label_12)
    self.verticalLayout.addLayout(self.formLayout)
    self.buttonBox = QDialogButtonBox(AboutDialog)
    self.buttonBox.setObjectName('buttonBox')
    self.buttonBox.setOrientation(Qt.Horizontal)
    self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel | QDialogButtonBox.Ok)
    self.verticalLayout.addWidget(self.buttonBox)
    self.retranslateUi(AboutDialog)
    self.buttonBox.accepted.connect(AboutDialog.accept)
    self.buttonBox.rejected.connect(AboutDialog.reject)
    QMetaObject.connectSlotsByName(AboutDialog)


def retranslateUi(self, AboutDialog):
    AboutDialog.setWindowTitle(QCoreApplication.translate('AboutDialog', 'About', None))
    self.label.setText(QCoreApplication.translate('AboutDialog', 'Software:', None))
    self.softwareLabel.setText(QCoreApplication.translate('AboutDialog', 'Mondo\nVersion: {}\nBuild Date: {}', None))
    self.label_4.setText(QCoreApplication.translate('AboutDialog', 'Support:', None))
    self.label_9.setText(QCoreApplication.translate('AboutDialog', 'This software is provided by EPRI "AS IS" and without customer support beyond such embodiments within the distribution of this software that may or may not provide such support.', None))
    self.label_5.setText(QCoreApplication.translate('AboutDialog', 'Copyright:', None))
    self.label_10.setText(QCoreApplication.translate('AboutDialog', 'Copyright (c) 2016 Electric Power Research Institute, Inc.\nCopyright (c) 2021 Suprock Technologies, LLC\nAll rights reserved.\n\nPermission to use, copy, modify, and distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.', None))
    self.label_6.setText(QCoreApplication.translate('AboutDialog', 'Developed by:', None))
    self.label_11.setText(QCoreApplication.translate('AboutDialog', 'Suprock Technologies\n45 Scott Hill Rd\nWarren, NH 03279', None))
    self.label_7.setText(QCoreApplication.translate('AboutDialog', 'Disclaimer:', None))
    self.label_12.setText(QCoreApplication.translate('AboutDialog', 'THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL EPRI BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.', None))

