# Source Generated with Decompyle++
# File: tmpvx0j2zen.marshal (Python 3.11)

self.darkMode.setChecked(self.preferences.dark_mode)
self.showSupplyChecks.setChecked(self.preferences.show_supplies)
self.automaticRGBCheckBox.setChecked(self.preferences.auto_rgb)
self.downsampleCheckBox.setChecked(self.preferences.downsample)
self.plotMeanCheckBox.setChecked(self.preferences.plot_mean)
self.unitPreferences.read_settings()
self.outputLocation.setText(self.preferences.base_dir)
self.outputLocation.setCursorPosition(0)
self.compressionLevel.setValue(self.preferences.compression_level)
self.runModbusCheckBox.setChecked(self.preferences.modbus_enable)
self.modbusPort.setValue(self.preferences.modbus_port)
self.enableUpload.setChecked(self.preferences.upload_enabled)
self.s3Bucket.setText(self.preferences.s3_bucket)
self.awsRegion.setText(self.preferences.aws_region)
self.uploadDirectory.setText(self.preferences.upload_directory)
self.uploadAccessKeyID.setText(self.preferences.access_key_id)
self.uploadSecretAccessKey.setText(self.preferences.secret_access_key)
self.uploadDeleteOriginal.setChecked(self.preferences.delete_original)
self.eventUploadEnabled.setChecked(self.preferences.event_upload_enabled)
self.enableAlertEmail.setChecked(self.preferences.alert_email_enabled)
self.fromAddress.setText(self.preferences.alert_from_address)
self.toAddress.setText(self.preferences.alert_to_address)
self.smtpHost.setText(self.preferences.alert_smtp_host)
self.smtpPort.setValue(self.preferences.alert_smtp_port)
security = self.preferences.alert_security.lower()
if security == 'starttls':
    self.useSTARTTLS.setChecked(True)
elif security == 'ssl':
    self.useSSL.setChecked(True)
elif security == '':
    self.noSecurity.setChecked(True)
else:
    self.useSTARTTLS.setChecked(True)
self.useAuthentication.setChecked(self.preferences.alert_use_auth)
self.smtpUser.setText(self.preferences.alert_smtp_user)
self.smtpPassword.setText(self.preferences.alert_smtp_password)
