# Source Generated with Decompyle++
# File: tmp4aunl91v.marshal (Python 3.11)

RFTestDialog.setWindowTitle(QCoreApplication.translate('RFTestDialog', 'RF Test', None))
self.stopChannelLabel.setText(QCoreApplication.translate('RFTestDialog', 'Stop Channel', None))
self.startFreqLabel.setText(QCoreApplication.translate('RFTestDialog', 'Start Frequency', None))
self.hopInterval.setSuffix(QCoreApplication.translate('RFTestDialog', ' ms', None))
self.rxCarrierRadioButton.setText(QCoreApplication.translate('RFTestDialog', 'RX Carrier', None))
self.hopCountLabel.setText(QCoreApplication.translate('RFTestDialog', 'Hop Count (0=∞)', None))
self.txCarrierRadioButton.setText(QCoreApplication.translate('RFTestDialog', 'TX Carrier', None))
self.hopIntervalLabel.setText(QCoreApplication.translate('RFTestDialog', 'Hop Interval', None))
self.testModeLabel.setText(QCoreApplication.translate('RFTestDialog', 'Test Mode', None))
self.fixedChannelLabel.setText(QCoreApplication.translate('RFTestDialog', 'Channel', None))
self.fixedDuration.setSuffix(QCoreApplication.translate('RFTestDialog', ' ms', None))
self.txModulatedRadioButton.setText(QCoreApplication.translate('RFTestDialog', 'TX Modulated Carrier', None))
self.testTypeLabel.setText(QCoreApplication.translate('RFTestDialog', 'Test Type', None))
self.startChannelLabel.setText(QCoreApplication.translate('RFTestDialog', 'Start Channel', None))
self.fixedRadioButton.setText(QCoreApplication.translate('RFTestDialog', 'Fixed Frequency', None))
self.stopFreqLabel.setText(QCoreApplication.translate('RFTestDialog', 'Stop Frequency', None))
self.fixedDurationLabel.setText(QCoreApplication.translate('RFTestDialog', 'Duration (0=∞)', None))
self.sweepRadioButton.setText(QCoreApplication.translate('RFTestDialog', 'Sweep', None))
self.centerFreqLabel.setText(QCoreApplication.translate('RFTestDialog', 'Center Frequency', None))
self.stopFreq.setText(QCoreApplication.translate('RFTestDialog', '2478 MHz', None))
self.startFreq.setText(QCoreApplication.translate('RFTestDialog', '2402 MHz', None))
self.centerFreq.setText(QCoreApplication.translate('RFTestDialog', '2402 MHz', None))
