# Source Generated with Decompyle++
# File: tmpk8p9q9vs.marshal (Python 3.11)

self.detailScanButton.clicked.connect(self.detail_scan)
self.connectButton.clicked.connect(self.connect_button_cb)
self.disconnectButton.clicked.connect(self.disconnect_button_cb)
self.goToRemoteButton.clicked.connect(self.show_remote_clicked)
self.deviceList.currentRowChanged.connect(self.current_row_changed_cb)
self.deviceList.itemDoubleClicked.connect(self.item_double_clicked_cb)
self.actionConnectNoStreaming.triggered.connect(self.connect_no_streaming_cb)
self.actionConnectSpecificBootloader.triggered.connect(self.connect_specific_bootloader_cb)
self.actionConnectSpecificSerial.triggered.connect(self.connect_specific_serial_cb)
self.actionClear.triggered.connect(self.clear_list)
self.update_device_list_timer = QtCore.QTimer(self)
self.update_device_list_timer.timeout.connect(self.update_device_list)
self.update_device_list_timer.start(250)
self.controller.scan_data.connect(self.scan_data_cb)
self.controller.remote_target_changed.connect(self.remote_target_changed_cb)
self.controller.scan_first_pass.connect(self.scan_first_pass_cb)
self.controller.state_changed_signal.connect(self.controller_state_changed_cb)
self.controller.remote_connected.connect(self.remote_connected_cb)
self.controller.remote_target_connected.connect(self.remote_target_connected_cb)
