# Source Generated with Decompyle++
# File: tmpe2crooju.marshal (Python 3.11)

if not CalibrationChannel.objectName():
    CalibrationChannel.setObjectName('CalibrationChannel')
CalibrationChannel.resize(257, 624)
self.verticalLayout = QVBoxLayout(CalibrationChannel)
self.verticalLayout.setObjectName('verticalLayout')
self.calibrationEnabled = QCheckBox(CalibrationChannel)
self.calibrationEnabled.setObjectName('calibrationEnabled')
self.calibrationEnabled.setChecked(True)
self.verticalLayout.addWidget(self.calibrationEnabled)
self.horizontalLayout_3 = QHBoxLayout()
self.horizontalLayout_3.setObjectName('horizontalLayout_3')
self.unitLabel = QLabel(CalibrationChannel)
self.unitLabel.setObjectName('unitLabel')
self.horizontalLayout_3.addWidget(self.unitLabel)
self.unit = QLabel(CalibrationChannel)
self.unit.setObjectName('unit')
self.horizontalLayout_3.addWidget(self.unit)
self.horizontalSpacer = QSpacerItem(0, 0, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
self.horizontalLayout_3.addItem(self.horizontalSpacer)
self.selectUnit = QPushButton(CalibrationChannel)
self.selectUnit.setObjectName('selectUnit')
self.horizontalLayout_3.addWidget(self.selectUnit)
self.verticalLayout.addLayout(self.horizontalLayout_3)
self.tabWidget = QTabWidget(CalibrationChannel)
self.tabWidget.setObjectName('tabWidget')
self.linearPage = QWidget()
self.linearPage.setObjectName('linearPage')
self.verticalLayout_2 = QVBoxLayout(self.linearPage)
self.verticalLayout_2.setObjectName('verticalLayout_2')
self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
self.horizontalLayout_5 = QHBoxLayout()
self.horizontalLayout_5.setObjectName('horizontalLayout_5')
self.linearCapture = QPushButton(self.linearPage)
self.linearCapture.setObjectName('linearCapture')
self.horizontalLayout_5.addWidget(self.linearCapture)
self.horizontalSpacer_6 = QSpacerItem(0, 0, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
self.horizontalLayout_5.addItem(self.horizontalSpacer_6)
self.plotButton = QPushButton(self.linearPage)
self.plotButton.setObjectName('plotButton')
self.plotButton.setEnabled(False)
self.horizontalLayout_5.addWidget(self.plotButton)
self.verticalLayout_2.addLayout(self.horizontalLayout_5)
self.linearTable = QTableWidget(self.linearPage)
if self.linearTable.columnCount() < 3:
    self.linearTable.setColumnCount(3)
_Ui_CalibrationChannel__qtablewidgetitem = QTableWidgetItem()
self.linearTable.setHorizontalHeaderItem(0, _Ui_CalibrationChannel__qtablewidgetitem)
_Ui_CalibrationChannel__qtablewidgetitem1 = QTableWidgetItem()
self.linearTable.setHorizontalHeaderItem(1, _Ui_CalibrationChannel__qtablewidgetitem1)
_Ui_CalibrationChannel__qtablewidgetitem2 = QTableWidgetItem()
self.linearTable.setHorizontalHeaderItem(2, _Ui_CalibrationChannel__qtablewidgetitem2)
self.linearTable.setObjectName('linearTable')
self.linearTable.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
self.linearTable.setSelectionMode(QAbstractItemView.NoSelection)
self.linearTable.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
self.verticalLayout_2.addWidget(self.linearTable)
self.graphicsView = PlotWidget(self.linearPage)
self.graphicsView.setObjectName('graphicsView')
self.verticalLayout_2.addWidget(self.graphicsView)
self.tabWidget.addTab(self.linearPage, '')
self.acPage = QWidget()
self.acPage.setObjectName('acPage')
self.formLayout = QFormLayout(self.acPage)
self.formLayout.setObjectName('formLayout')
self.formLayout.setContentsMargins(0, 0, 0, 0)
self.capturedMagnitudeLabel = QLabel(self.acPage)
self.capturedMagnitudeLabel.setObjectName('capturedMagnitudeLabel')
self.formLayout.setWidget(1, QFormLayout.LabelRole, self.capturedMagnitudeLabel)
self.capturedOffsetLabel = QLabel(self.acPage)
self.capturedOffsetLabel.setObjectName('capturedOffsetLabel')
self.formLayout.setWidget(2, QFormLayout.LabelRole, self.capturedOffsetLabel)
self.actualMagnitudeLabel = QLabel(self.acPage)
self.actualMagnitudeLabel.setObjectName('actualMagnitudeLabel')
self.formLayout.setWidget(3, QFormLayout.LabelRole, self.actualMagnitudeLabel)
self.actualOffsetLabel = QLabel(self.acPage)
self.actualOffsetLabel.setObjectName('actualOffsetLabel')
self.formLayout.setWidget(4, QFormLayout.LabelRole, self.actualOffsetLabel)
self.capturedMagnitude = UnitFormatterDoubleSpinBox(self.acPage)
self.capturedMagnitude.setObjectName('capturedMagnitude')
self.capturedMagnitude.setValue(1)
self.formLayout.setWidget(1, QFormLayout.FieldRole, self.capturedMagnitude)
self.actualMagnitude = UnitFormatterDoubleSpinBox(self.acPage)
self.actualMagnitude.setObjectName('actualMagnitude')
self.actualMagnitude.setValue(1)
self.formLayout.setWidget(3, QFormLayout.FieldRole, self.actualMagnitude)
self.capturedOffset = UnitFormatterDoubleSpinBox(self.acPage)
self.capturedOffset.setObjectName('capturedOffset')
self.formLayout.setWidget(2, QFormLayout.FieldRole, self.capturedOffset)
self.actualOffset = UnitFormatterDoubleSpinBox(self.acPage)
self.actualOffset.setObjectName('actualOffset')
self.formLayout.setWidget(4, QFormLayout.FieldRole, self.actualOffset)
self.horizontalLayout_4 = QHBoxLayout()
self.horizontalLayout_4.setObjectName('horizontalLayout_4')
self.acCapture = QPushButton(self.acPage)
self.acCapture.setObjectName('acCapture')
self.horizontalLayout_4.addWidget(self.acCapture)
self.horizontalSpacer_2 = QSpacerItem(0, 0, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
self.horizontalLayout_4.addItem(self.horizontalSpacer_2)
self.formLayout.setLayout(0, QFormLayout.SpanningRole, self.horizontalLayout_4)
self.tabWidget.addTab(self.acPage, '')
self.verticalLayout.addWidget(self.tabWidget)
self.scaleOffsetLayout = QFormLayout()
self.scaleOffsetLayout.setObjectName('scaleOffsetLayout')
self.scaleLabel = QLabel(CalibrationChannel)
self.scaleLabel.setObjectName('scaleLabel')
self.scaleOffsetLayout.setWidget(0, QFormLayout.LabelRole, self.scaleLabel)
self.scale = QLineEdit(CalibrationChannel)
self.scale.setObjectName('scale')
self.scale.setReadOnly(True)
self.scaleOffsetLayout.setWidget(0, QFormLayout.FieldRole, self.scale)
self.offset = QLineEdit(CalibrationChannel)
self.offset.setObjectName('offset')
self.offset.setReadOnly(True)
self.scaleOffsetLayout.setWidget(1, QFormLayout.FieldRole, self.offset)
self.offsetLabel = QLabel(CalibrationChannel)
self.offsetLabel.setObjectName('offsetLabel')
self.scaleOffsetLayout.setWidget(1, QFormLayout.LabelRole, self.offsetLabel)
self.verticalLayout.addLayout(self.scaleOffsetLayout)
QWidget.setTabOrder(self.calibrationEnabled, self.selectUnit)
QWidget.setTabOrder(self.selectUnit, self.acCapture)
QWidget.setTabOrder(self.acCapture, self.capturedMagnitude)
QWidget.setTabOrder(self.capturedMagnitude, self.capturedOffset)
QWidget.setTabOrder(self.capturedOffset, self.actualMagnitude)
QWidget.setTabOrder(self.actualMagnitude, self.actualOffset)
QWidget.setTabOrder(self.actualOffset, self.linearCapture)
QWidget.setTabOrder(self.linearCapture, self.linearTable)
QWidget.setTabOrder(self.linearTable, self.scale)
self.retranslateUi(CalibrationChannel)
self.tabWidget.setCurrentIndex(0)
QMetaObject.connectSlotsByName(CalibrationChannel)
