# Source Generated with Decompyle++
# File: tmpsuevf2xg.marshal (Python 3.11)

self.calibrationEnabled.setText(QCoreApplication.translate('CalibrationChannel', 'Calibrate channel', None))
self.unitLabel.setText(QCoreApplication.translate('CalibrationChannel', 'Unit:', None))
self.unit.setText(QCoreApplication.translate('CalibrationChannel', 'Unit', None))
self.selectUnit.setText(QCoreApplication.translate('CalibrationChannel', 'Select Unit', None))
self.linearCapture.setText(QCoreApplication.translate('CalibrationChannel', 'Capture', None))
self.plotButton.setText(QCoreApplication.translate('CalibrationChannel', 'Plot', None))
_Ui_CalibrationChannel___qtablewidgetitem = self.linearTable.horizontalHeaderItem(0)
_Ui_CalibrationChannel___qtablewidgetitem.setText(QCoreApplication.translate('CalibrationChannel', 'Captured', None))
_Ui_CalibrationChannel___qtablewidgetitem1 = self.linearTable.horizontalHeaderItem(1)
_Ui_CalibrationChannel___qtablewidgetitem1.setText(QCoreApplication.translate('CalibrationChannel', 'Actual', None))
_Ui_CalibrationChannel___qtablewidgetitem2 = self.linearTable.horizontalHeaderItem(2)
_Ui_CalibrationChannel___qtablewidgetitem2.setText(QCoreApplication.translate('CalibrationChannel', 'Delete', None))
self.tabWidget.setTabText(self.tabWidget.indexOf(self.linearPage), QCoreApplication.translate('CalibrationChannel', '1st Order Linear', None))
self.capturedMagnitudeLabel.setText(QCoreApplication.translate('CalibrationChannel', 'Captured RMS Magnitude', None))
self.capturedOffsetLabel.setText(QCoreApplication.translate('CalibrationChannel', 'Captured DC Offset', None))
self.actualMagnitudeLabel.setText(QCoreApplication.translate('CalibrationChannel', 'Actual RMS Magnitude', None))
self.actualOffsetLabel.setText(QCoreApplication.translate('CalibrationChannel', 'Actual DC Offset', None))
self.acCapture.setText(QCoreApplication.translate('CalibrationChannel', 'Capture', None))
self.tabWidget.setTabText(self.tabWidget.indexOf(self.acPage), QCoreApplication.translate('CalibrationChannel', 'AC RMS', None))
self.scaleLabel.setText(QCoreApplication.translate('CalibrationChannel', 'Scale', None))
self.offsetLabel.setText(QCoreApplication.translate('CalibrationChannel', 'Offset', None))
