# Source Generated with Decompyle++
# File: tmpc23yknz2.marshal (Python 3.11)

self.bootloader_fg_brush = QtGui.QBrush(QtGui.QColor(QtCore.Qt.GlobalColor.black))
self.bootloader_bg_brush = QtGui.QBrush(QtGui.QColor(QtCore.Qt.GlobalColor.yellow))
self.default_font = QtGui.QFont()
self.bootloader_font = QtGui.QFont()
self.bootloader_font.setBold(True)
header = self.tableWidget.horizontalHeader()
header.setSectionResizeMode(QtWidgets.QHeaderView.ResizeMode.ResizeToContents)
self.rescanButton = self.buttonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Reset)
self.rescanButton.setText(self.tr('Rescan'))
self.rescanButton.clicked.connect(self.rescan)
selection_model = self.tableWidget.selectionModel()
selection_model.selectionChanged.connect(self.selection_changed)
self.tableWidget.doubleClicked.connect(self.double_click_cb)
self.tableWidget.sortByColumn(0, QtCore.Qt.SortOrder.AscendingOrder)
self.tableWidget.setSortingEnabled(True)
self.rescan_timer = QtCore.QTimer(self)
self.rescan_timer.timeout.connect(self.rescan)
self.automaticRescan.toggled.connect(self.set_automatic_rescan)
self.automaticRescan.setChecked(self.preferences.automatic_rescan)
self.finished.connect(self.rescan_timer.stop)
