# Source Generated with Decompyle++
# File: tmphgmdibt6.marshal (Python 3.11)

if not TCPConnectDialog.objectName():
    TCPConnectDialog.setObjectName('TCPConnectDialog')
TCPConnectDialog.resize(341, 119)
self.formLayout = QFormLayout(TCPConnectDialog)
self.formLayout.setObjectName('formLayout')
self.hostnameLabel = QLabel(TCPConnectDialog)
self.hostnameLabel.setObjectName('hostnameLabel')
self.formLayout.setWidget(0, QFormLayout.LabelRole, self.hostnameLabel)
self.hostname = QLineEdit(TCPConnectDialog)
self.hostname.setObjectName('hostname')
self.hostname.setMinimumSize(QSize(200, 0))
self.formLayout.setWidget(0, QFormLayout.FieldRole, self.hostname)
self.portLabel = QLabel(TCPConnectDialog)
self.portLabel.setObjectName('portLabel')
self.formLayout.setWidget(1, QFormLayout.LabelRole, self.portLabel)
self.port = QSpinBox(TCPConnectDialog)
self.port.setObjectName('port')
self.port.setMinimum(1)
self.port.setMaximum(65535)
self.port.setValue(5760)
self.formLayout.setWidget(1, QFormLayout.FieldRole, self.port)
self.serialLabel = QLabel(TCPConnectDialog)
self.serialLabel.setObjectName('serialLabel')
self.formLayout.setWidget(2, QFormLayout.LabelRole, self.serialLabel)
self.serial = QLineEdit(TCPConnectDialog)
self.serial.setObjectName('serial')
self.formLayout.setWidget(2, QFormLayout.FieldRole, self.serial)
self.buttonBox = QDialogButtonBox(TCPConnectDialog)
self.buttonBox.setObjectName('buttonBox')
self.buttonBox.setOrientation(Qt.Horizontal)
self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel | QDialogButtonBox.Ok)
self.formLayout.setWidget(3, QFormLayout.SpanningRole, self.buttonBox)
self.retranslateUi(TCPConnectDialog)
self.buttonBox.accepted.connect(TCPConnectDialog.accept)
self.buttonBox.rejected.connect(TCPConnectDialog.reject)
QMetaObject.connectSlotsByName(TCPConnectDialog)
