# Source Generated with Decompyle++
# File: tmpqb8uv74g.marshal (Python 3.11)

DateTimeSubsetDialog.setWindowTitle(QCoreApplication.translate('DateTimeSubsetDialog', 'Select Data Range', None))
self.useAllData.setText(QCoreApplication.translate('DateTimeSubsetDialog', 'Use all data', None))
self.startLabel.setText(QCoreApplication.translate('DateTimeSubsetDialog', 'Start Time (UTC):', None))
self.startDateTime.setDisplayFormat(QCoreApplication.translate('DateTimeSubsetDialog', 'yyyy-MM-ddThh:mm:ssZ', None))
self.endLabel.setText(QCoreApplication.translate('DateTimeSubsetDialog', 'End Time (UTC):', None))
self.endDateTime.setDisplayFormat(QCoreApplication.translate('DateTimeSubsetDialog', 'yyyy-MM-ddThh:mm:ssZ', None))
self.durationLabel.setText(QCoreApplication.translate('DateTimeSubsetDialog', 'Duration:', None))
self.label.setText(QCoreApplication.translate('DateTimeSubsetDialog', 'Relative Start Time', None))
self.label_2.setText(QCoreApplication.translate('DateTimeSubsetDialog', 'Relative End Time', None))
self.startSeconds.setSuffix(QCoreApplication.translate('DateTimeSubsetDialog', ' s', None))
self.endSeconds.setSuffix(QCoreApplication.translate('DateTimeSubsetDialog', ' s', None))
self.duration.setSuffix(QCoreApplication.translate('DateTimeSubsetDialog', ' s', None))
self.useSubset.setText(QCoreApplication.translate('DateTimeSubsetDialog', 'Use data within range', None))
self.allStartLabel.setText(QCoreApplication.translate('DateTimeSubsetDialog', 'Start Time (UTC):', None))
self.allStart.setText(QCoreApplication.translate('DateTimeSubsetDialog', '1/1/2000 12:00:00 AM', None))
self.allEndLabel.setText(QCoreApplication.translate('DateTimeSubsetDialog', 'End Time (UTC):', None))
self.allEnd.setText(QCoreApplication.translate('DateTimeSubsetDialog', '1/1/2000 12:00:00 AM', None))
self.allDurationLabel.setText(QCoreApplication.translate('DateTimeSubsetDialog', 'Duration:', None))
self.allDuration.setText(QCoreApplication.translate('DateTimeSubsetDialog', '0 s', None))
