# Source Generated with Decompyle++
# File: tmpp4do8xft.marshal (Python 3.11)

from PySide6.QtCore import QCoreApplication, QDate, QDateTime, QLocale, QMetaObject, QObject, QPoint, QRect, QSize, QTime, QUrl, Qt
from PySide6.QtGui import QBrush, QColor, QConicalGradient, QCursor, QFont, QFontDatabase, QGradient, QIcon, QImage, QKeySequence, QLinearGradient, QPainter, QPalette, QPixmap, QRadialGradient, QTransform
from PySide6.QtWidgets import QAbstractButton, QApplication, QDialog, QDialogButtonBox, QFormLayout, QHBoxLayout, QLabel, QLineEdit, QRadioButton, QSizePolicy, QSpinBox, QWidget

class Ui_DownloadFirmwareDialog(object):
    
    def setupUi(self, DownloadFirmwareDialog):
        if not DownloadFirmwareDialog.objectName():
            DownloadFirmwareDialog.setObjectName('DownloadFirmwareDialog')
        DownloadFirmwareDialog.resize(374, 147)
        self.formLayout = QFormLayout(DownloadFirmwareDialog)
        self.formLayout.setObjectName('formLayout')
        self.formLayout.setFieldGrowthPolicy(QFormLayout.AllNonFixedFieldsGrow)
        self.boardRadioButton = QRadioButton(DownloadFirmwareDialog)
        self.boardRadioButton.setObjectName('boardRadioButton')
        self.boardRadioButton.setChecked(False)
        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.boardRadioButton)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.boardName = QLineEdit(DownloadFirmwareDialog)
        self.boardName.setObjectName('boardName')
        self.boardName.setMinimumSize(QSize(200, 0))
        self.horizontalLayout.addWidget(self.boardName)
        self.revLabel = QLabel(DownloadFirmwareDialog)
        self.revLabel.setObjectName('revLabel')
        self.horizontalLayout.addWidget(self.revLabel)
        self.boardRev = QSpinBox(DownloadFirmwareDialog)
        self.boardRev.setObjectName('boardRev')
        self.boardRev.setMaximum(255)
        self.boardRev.setValue(1)
        self.horizontalLayout.addWidget(self.boardRev)
        self.formLayout.setLayout(0, QFormLayout.FieldRole, self.horizontalLayout)
        self.repoRadioButton = QRadioButton(DownloadFirmwareDialog)
        self.repoRadioButton.setObjectName('repoRadioButton')
        self.formLayout.setWidget(1, QFormLayout.LabelRole, self.repoRadioButton)
        self.repoName = QLineEdit(DownloadFirmwareDialog)
        self.repoName.setObjectName('repoName')
        self.repoName.setEnabled(False)
        self.formLayout.setWidget(1, QFormLayout.FieldRole, self.repoName)
        self.branchRadioButton = QRadioButton(DownloadFirmwareDialog)
        self.branchRadioButton.setObjectName('branchRadioButton')
        self.branchRadioButton.setChecked(True)
        self.formLayout.setWidget(2, QFormLayout.LabelRole, self.branchRadioButton)
        self.branchName = QLineEdit(DownloadFirmwareDialog)
        self.branchName.setObjectName('branchName')
        self.formLayout.setWidget(2, QFormLayout.FieldRole, self.branchName)
        self.commitRadioButton = QRadioButton(DownloadFirmwareDialog)
        self.commitRadioButton.setObjectName('commitRadioButton')
        self.formLayout.setWidget(3, QFormLayout.LabelRole, self.commitRadioButton)
        self.commitHash = QLineEdit(DownloadFirmwareDialog)
        self.commitHash.setObjectName('commitHash')
        self.commitHash.setEnabled(False)
        self.formLayout.setWidget(3, QFormLayout.FieldRole, self.commitHash)
        self.buttonBox = QDialogButtonBox(DownloadFirmwareDialog)
        self.buttonBox.setObjectName('buttonBox')
        self.buttonBox.setOrientation(Qt.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel | QDialogButtonBox.Ok)
        self.formLayout.setWidget(4, QFormLayout.SpanningRole, self.buttonBox)
        QWidget.setTabOrder(self.boardRadioButton, self.boardName)
        QWidget.setTabOrder(self.boardName, self.boardRev)
        QWidget.setTabOrder(self.boardRev, self.repoRadioButton)
        QWidget.setTabOrder(self.repoRadioButton, self.repoName)
        QWidget.setTabOrder(self.repoName, self.branchRadioButton)
        QWidget.setTabOrder(self.branchRadioButton, self.branchName)
        QWidget.setTabOrder(self.branchName, self.commitRadioButton)
        QWidget.setTabOrder(self.commitRadioButton, self.commitHash)
        QWidget.setTabOrder(self.commitHash, self.buttonBox)
        self.retranslateUi(DownloadFirmwareDialog)
        self.buttonBox.accepted.connect(DownloadFirmwareDialog.accept)
        self.buttonBox.rejected.connect(DownloadFirmwareDialog.reject)
        self.boardRadioButton.toggled.connect(self.boardName.setEnabled)
        self.boardRadioButton.toggled.connect(self.boardRev.setEnabled)
        self.repoRadioButton.toggled.connect(self.repoName.setEnabled)
        self.branchRadioButton.toggled.connect(self.branchName.setEnabled)
        self.commitRadioButton.toggled.connect(self.commitHash.setEnabled)
        QMetaObject.connectSlotsByName(DownloadFirmwareDialog)

    
    def retranslateUi(self, DownloadFirmwareDialog):
        DownloadFirmwareDialog.setWindowTitle(QCoreApplication.translate('DownloadFirmwareDialog', 'Download Firmware', None))
        self.boardRadioButton.setText(QCoreApplication.translate('DownloadFirmwareDialog', 'Board', None))
        self.revLabel.setText(QCoreApplication.translate('DownloadFirmwareDialog', 'Rev', None))
        self.repoRadioButton.setText(QCoreApplication.translate('DownloadFirmwareDialog', 'Repository', None))
        self.branchRadioButton.setText(QCoreApplication.translate('DownloadFirmwareDialog', 'Branch', None))
        self.branchName.setText(QCoreApplication.translate('DownloadFirmwareDialog', 'master', None))
        self.commitRadioButton.setText(QCoreApplication.translate('DownloadFirmwareDialog', 'Commit', None))


