# Source Generated with Decompyle++
# File: tmp_jo231w0.marshal (Python 3.11)

DeviceTab.setWindowTitle(QCoreApplication.translate('DeviceTab', 'Device Tab', None))
self.actionSetUserTag1.setText(QCoreApplication.translate('DeviceTab', 'Set User Tag 1', None))
self.actionSetUserTag2.setText(QCoreApplication.translate('DeviceTab', 'Set User Tag 2', None))
self.actionSetUserTag2.setToolTip(QCoreApplication.translate('DeviceTab', 'Set User Tag 2', None))
self.actionEditDeviceSettings.setText(QCoreApplication.translate('DeviceTab', 'Edit Device Settings', None))
self.actionShowDeviceInfo.setText(QCoreApplication.translate('DeviceTab', 'More Device Info', None))
self.actionShowDeviceInfo.setToolTip(QCoreApplication.translate('DeviceTab', 'More Device Info', None))
self.actionFirmwareLatestStable.setText(QCoreApplication.translate('DeviceTab', 'Latest Stable', None))
self.actionFirmwareLatestStable.setToolTip(QCoreApplication.translate('DeviceTab', 'Update Firmware From Latest Stable', None))
self.actionShowPacketStats.setText(QCoreApplication.translate('DeviceTab', 'Show Packet Stats', None))
self.actionChangeActiveStreams.setText(QCoreApplication.translate('DeviceTab', 'Change Active Streams', None))
self.actionRunTests.setText(QCoreApplication.translate('DeviceTab', 'Run Hardware Tests', None))
self.actionSetDeviceMode.setText(QCoreApplication.translate('DeviceTab', 'Set Device Mode', None))
self.actionFirmwareFromBranch.setText(QCoreApplication.translate('DeviceTab', 'From Branch', None))
self.actionFirmwareFromBranch.setToolTip(QCoreApplication.translate('DeviceTab', 'Update Firmware From Branch', None))
self.actionFirmwareFromCommit.setText(QCoreApplication.translate('DeviceTab', 'From Specific Commit', None))
self.actionFirmwareFromCommit.setToolTip(QCoreApplication.translate('DeviceTab', 'Update Firmware From Specific Commit', None))
self.actionFirmwareFromFile.setText(QCoreApplication.translate('DeviceTab', 'From File', None))
self.actionFirmwareFromFile.setToolTip(QCoreApplication.translate('DeviceTab', 'Update Firmware From File', None))
self.actionForceRunBootloader.setText(QCoreApplication.translate('DeviceTab', 'Force Run Bootloader', None))
self.actionForceRunApplication.setText(QCoreApplication.translate('DeviceTab', 'Force Run Application', None))
self.actionForceRunApplication.setToolTip(QCoreApplication.translate('DeviceTab', 'Force Run Application', None))
self.actionForceReset.setText(QCoreApplication.translate('DeviceTab', 'Force Reset', None))
self.actionForceReset.setToolTip(QCoreApplication.translate('DeviceTab', 'Force Reset', None))
self.actionRaiseException.setText(QCoreApplication.translate('DeviceTab', 'Raise Exception', None))
self.actionRaiseException.setToolTip(QCoreApplication.translate('DeviceTab', 'Raise Exception', None))
self.actionRecoverNVM.setText(QCoreApplication.translate('DeviceTab', 'Recover NVM', None))
self.actionRecoverNVM.setToolTip(QCoreApplication.translate('DeviceTab', 'Recover NVM', None))
self.actionCalibrate.setText(QCoreApplication.translate('DeviceTab', 'Start Calibration', None))
self.actionShakerCalibrate.setText(QCoreApplication.translate('DeviceTab', '1g RMS Shaker Calibration', None))
self.actionShakerCalibrate.setToolTip(QCoreApplication.translate('DeviceTab', '1g RMS Shaker Calibration', None))
self.actionCopySerialNumber.setText(QCoreApplication.translate('DeviceTab', 'Copy Serial Number', None))
self.actionFlushLostPackets.setText(QCoreApplication.translate('DeviceTab', 'Flush Lost Packets', None))
self.actionFlushLostPackets.setToolTip(QCoreApplication.translate('DeviceTab', 'Flush Lost Packets', None))
self.actionRFTest.setText(QCoreApplication.translate('DeviceTab', 'RF Test', None))
self.actionRFTest.setToolTip(QCoreApplication.translate('DeviceTab', 'RF Test', None))
self.actionConnectivity.setText(QCoreApplication.translate('DeviceTab', 'Connectivity', None))
self.actionConnectivity.setToolTip(QCoreApplication.translate('DeviceTab', 'Connectivity', None))
self.graphChannelLabel.setText(QCoreApplication.translate('DeviceTab', 'Graph Channel:', None))
self.fftSubchannelLabel.setText(QCoreApplication.translate('DeviceTab', 'Frequency Subchannel:', None))
self.nvmModifiedIndicator.setText(QCoreApplication.translate('DeviceTab', 'NVM Modified', None))
self.bootloaderIndicator.setText(QCoreApplication.translate('DeviceTab', 'Bootloader', None))
self.editDeviceSettings.setText(QCoreApplication.translate('DeviceTab', 'PushButton', None))
self.menuButton.setText(QCoreApplication.translate('DeviceTab', 'Menu', None))
self.closeButton.setText(QCoreApplication.translate('DeviceTab', 'Close', None))
self.statusLabel.setText(QCoreApplication.translate('DeviceTab', 'Disconnected', None))
self.collapseButton.setText(QCoreApplication.translate('DeviceTab', 'Collapse', None))
self.channelGroupBox.setTitle(QCoreApplication.translate('DeviceTab', 'Channels', None))
self.meanLabel.setText(QCoreApplication.translate('DeviceTab', 'Mean (1s)', None))
self.samplingRateLabel.setText(QCoreApplication.translate('DeviceTab', 'Sampling Rate', None))
self.stdDevLabel.setText(QCoreApplication.translate('DeviceTab', 'Std Dev (1s)', None))
self.channelLabel.setText('')
self.deviceInfoGroupBox.setTitle(QCoreApplication.translate('DeviceTab', 'Device Info', None))
self.userTag2.setText(QCoreApplication.translate('DeviceTab', 'User Tag 2', None))
self.boardInfo.setText(QCoreApplication.translate('DeviceTab', 'Board Info', None))
self.branchLabel.setText(QCoreApplication.translate('DeviceTab', 'Branch:', None))
self.deviceInfo.setText(QCoreApplication.translate('DeviceTab', 'More', None))
self.buildDateLabel.setText(QCoreApplication.translate('DeviceTab', 'Build Date:', None))
self.copySerialNumber.setText(QCoreApplication.translate('DeviceTab', 'Copy', None))
self.setUserTag1.setText(QCoreApplication.translate('DeviceTab', 'Set', None))
self.buildInfo.setText(QCoreApplication.translate('DeviceTab', 'Build Info', None))
self.branch.setText(QCoreApplication.translate('DeviceTab', 'branch', None))
self.serialNumberLabel.setText(QCoreApplication.translate('DeviceTab', 'Serial Number:', None))
self.battery.setText(QCoreApplication.translate('DeviceTab', 'battery', None))
self.boardInfoLabel.setText(QCoreApplication.translate('DeviceTab', 'Board Info:', None))
self.userTag2Label.setText(QCoreApplication.translate('DeviceTab', 'User Tag 2:', None))
self.setUserTag2.setText(QCoreApplication.translate('DeviceTab', 'Set', None))
self.buildInfoLabel.setText(QCoreApplication.translate('DeviceTab', 'Build Info:', None))
self.serialNumber.setText(QCoreApplication.translate('DeviceTab', 'Serial Number', None))
self.userTag1Label.setText(QCoreApplication.translate('DeviceTab', 'User Tag 1:', None))
self.buildDate.setText(QCoreApplication.translate('DeviceTab', 'Build Date', None))
self.userTag1.setText(QCoreApplication.translate('DeviceTab', 'User Tag 1', None))
self.batteryLabel.setText(QCoreApplication.translate('DeviceTab', 'Battery:', None))
self.suppliesLabel.setText(QCoreApplication.translate('DeviceTab', 'Supplies:', None))
self.supplies.setText(QCoreApplication.translate('DeviceTab', 'supplies', None))
self.LEDGroupBox.setTitle(QCoreApplication.translate('DeviceTab', 'LEDs', None))
self.logGroupBox.setTitle(QCoreApplication.translate('DeviceTab', 'Log', None))
self.scheduleLabel.setText(QCoreApplication.translate('DeviceTab', '1 active trigger', None))
self.recentLostPacketsLabel.setText(QCoreApplication.translate('DeviceTab', 'Lost Packets (last 20 s):', None))
self.recentLostPackets.setText(QCoreApplication.translate('DeviceTab', '0', None))
