# Source Generated with Decompyle++
# File: tmpsgzhxi6_.marshal (Python 3.11)

PlotMainWindow.setWindowTitle(QCoreApplication.translate('PlotMainWindow', 'Acheron', None))
self.actionRescanUSB.setText(QCoreApplication.translate('PlotMainWindow', 'Rescan USB', None))
self.actionExit.setText(QCoreApplication.translate('PlotMainWindow', 'Exit', None))
self.actionPreferences.setText(QCoreApplication.translate('PlotMainWindow', 'Preferences...', None))
self.actionAbout.setText(QCoreApplication.translate('PlotMainWindow', 'About...', None))
self.actionDisableStreaming.setText(QCoreApplication.translate('PlotMainWindow', 'Disable Streaming', None))
self.actionDisableArchiving.setText(QCoreApplication.translate('PlotMainWindow', 'Disable Archiving', None))
self.actionFindTCPDevices.setText(QCoreApplication.translate('PlotMainWindow', 'Find TCP Devices...', None))
self.actionEnableRFPower.setText(QCoreApplication.translate('PlotMainWindow', 'Enable RF Power (0)', None))
self.actionDisableRFPower.setText(QCoreApplication.translate('PlotMainWindow', 'Disable RF Power (0)', None))
self.actionClosableTabs.setText(QCoreApplication.translate('PlotMainWindow', 'Easy Close Tabs', None))
self.actionUpdateLatestStable.setText(QCoreApplication.translate('PlotMainWindow', 'Latest Stable', None))
self.actionUpdateSpecificBranch.setText(QCoreApplication.translate('PlotMainWindow', 'Specific Branch...', None))
self.actionUpdateSpecificCommit.setText(QCoreApplication.translate('PlotMainWindow', 'Specific Commit..', None))
self.actionUpdateCurrentBranch.setText(QCoreApplication.translate('PlotMainWindow', 'Latest branch', None))
self.actionDownloadFirmware.setText(QCoreApplication.translate('PlotMainWindow', 'Download Firmware...', None))
self.actionMarkFiles.setText(QCoreApplication.translate('PlotMainWindow', 'Mark Files...', None))
self.actionMarkDirectory.setText(QCoreApplication.translate('PlotMainWindow', 'Mark Directory...', None))
self.actionConnectTCPDevice.setText(QCoreApplication.translate('PlotMainWindow', 'Manually Connect TCP Device...', None))
self.actionChannelTable.setText(QCoreApplication.translate('PlotMainWindow', 'Channel Table...', None))
self.actionShowLogs.setText(QCoreApplication.translate('PlotMainWindow', 'Show Logs on Disk...', None))
self.actionShowLogs.setToolTip(QCoreApplication.translate('PlotMainWindow', 'Show Logs on Disk', None))
self.actionShowConfig.setText(QCoreApplication.translate('PlotMainWindow', 'Show Config on Disk...', None))
self.actionReloadSchedule.setText(QCoreApplication.translate('PlotMainWindow', 'Reload Schedule From Disk', None))
_Ui_PlotMainWindow___qtreewidgetitem = self.treeWidget.headerItem()
_Ui_PlotMainWindow___qtreewidgetitem.setText(8, QCoreApplication.translate('PlotMainWindow', 'Inactive Triggers', None))
_Ui_PlotMainWindow___qtreewidgetitem.setText(7, QCoreApplication.translate('PlotMainWindow', 'Active Triggers', None))
_Ui_PlotMainWindow___qtreewidgetitem.setText(6, QCoreApplication.translate('PlotMainWindow', 'Schedule Items', None))
_Ui_PlotMainWindow___qtreewidgetitem.setText(5, QCoreApplication.translate('PlotMainWindow', 'Build Date', None))
_Ui_PlotMainWindow___qtreewidgetitem.setText(4, QCoreApplication.translate('PlotMainWindow', 'Build Info', None))
_Ui_PlotMainWindow___qtreewidgetitem.setText(3, QCoreApplication.translate('PlotMainWindow', 'Board Info', None))
_Ui_PlotMainWindow___qtreewidgetitem.setText(2, QCoreApplication.translate('PlotMainWindow', 'Tag 2', None))
_Ui_PlotMainWindow___qtreewidgetitem.setText(1, QCoreApplication.translate('PlotMainWindow', 'Tag 1', None))
_Ui_PlotMainWindow___qtreewidgetitem.setText(0, QCoreApplication.translate('PlotMainWindow', 'Serial Number', None))
self.tabWidget.setTabText(self.tabWidget.indexOf(self.treeWidget), QCoreApplication.translate('PlotMainWindow', 'Devices', None))
self.warningLabel.setText(QCoreApplication.translate('PlotMainWindow', 'Warning: Archiving Disabled', None))
self.uploadRateLabel.setText(QCoreApplication.translate('PlotMainWindow', '350 kB/s', None))
self.uploadProgress.setFormat(QCoreApplication.translate('PlotMainWindow', '%v/%m (%p%)', None))
self.uploadNameLabel.setText(QCoreApplication.translate('PlotMainWindow', '20181029T2241Z_HSS2143.apd', None))
self.activeTriggerLabel.setText(QCoreApplication.translate('PlotMainWindow', 'Active Triggers: test', None))
self.datetimeLabel.setText(QCoreApplication.translate('PlotMainWindow', '0000-00-00T00:00:00Z', None))
self.menuFile.setTitle(QCoreApplication.translate('PlotMainWindow', 'File', None))
self.menuStreaming.setTitle(QCoreApplication.translate('PlotMainWindow', 'Streaming', None))
self.menuSettings.setTitle(QCoreApplication.translate('PlotMainWindow', 'Settings', None))
self.menuHelp.setTitle(QCoreApplication.translate('PlotMainWindow', 'Help', None))
self.menuCheckForUpdates.setTitle(QCoreApplication.translate('PlotMainWindow', 'Check for Updates', None))
self.menuDevices.setTitle(QCoreApplication.translate('PlotMainWindow', 'Devices', None))
self.menuTools.setTitle(QCoreApplication.translate('PlotMainWindow', 'Tools', None))
self.menuMarkForUpload.setTitle(QCoreApplication.translate('PlotMainWindow', 'Mark for Upload', None))
