# Source Generated with Decompyle++
# File: tmpt3wkfctz.marshal (Python 3.11)

if not PlotMainWindow.objectName():
    PlotMainWindow.setObjectName('PlotMainWindow')
PlotMainWindow.resize(1200, 800)
self.actionRescanUSB = QAction(PlotMainWindow)
self.actionRescanUSB.setObjectName('actionRescanUSB')
self.actionExit = QAction(PlotMainWindow)
self.actionExit.setObjectName('actionExit')
self.actionPreferences = QAction(PlotMainWindow)
self.actionPreferences.setObjectName('actionPreferences')
self.actionAbout = QAction(PlotMainWindow)
self.actionAbout.setObjectName('actionAbout')
self.actionDisableStreaming = QAction(PlotMainWindow)
self.actionDisableStreaming.setObjectName('actionDisableStreaming')
self.actionDisableStreaming.setCheckable(True)
self.actionDisableArchiving = QAction(PlotMainWindow)
self.actionDisableArchiving.setObjectName('actionDisableArchiving')
self.actionDisableArchiving.setCheckable(True)
self.actionFindTCPDevices = QAction(PlotMainWindow)
self.actionFindTCPDevices.setObjectName('actionFindTCPDevices')
self.actionEnableRFPower = QAction(PlotMainWindow)
self.actionEnableRFPower.setObjectName('actionEnableRFPower')
self.actionDisableRFPower = QAction(PlotMainWindow)
self.actionDisableRFPower.setObjectName('actionDisableRFPower')
self.actionClosableTabs = QAction(PlotMainWindow)
self.actionClosableTabs.setObjectName('actionClosableTabs')
self.actionClosableTabs.setCheckable(True)
self.actionUpdateLatestStable = QAction(PlotMainWindow)
self.actionUpdateLatestStable.setObjectName('actionUpdateLatestStable')
self.actionUpdateSpecificBranch = QAction(PlotMainWindow)
self.actionUpdateSpecificBranch.setObjectName('actionUpdateSpecificBranch')
self.actionUpdateSpecificCommit = QAction(PlotMainWindow)
self.actionUpdateSpecificCommit.setObjectName('actionUpdateSpecificCommit')
self.actionUpdateCurrentBranch = QAction(PlotMainWindow)
self.actionUpdateCurrentBranch.setObjectName('actionUpdateCurrentBranch')
self.actionDownloadFirmware = QAction(PlotMainWindow)
self.actionDownloadFirmware.setObjectName('actionDownloadFirmware')
self.actionMarkFiles = QAction(PlotMainWindow)
self.actionMarkFiles.setObjectName('actionMarkFiles')
self.actionMarkDirectory = QAction(PlotMainWindow)
self.actionMarkDirectory.setObjectName('actionMarkDirectory')
self.actionConnectTCPDevice = QAction(PlotMainWindow)
self.actionConnectTCPDevice.setObjectName('actionConnectTCPDevice')
self.actionChannelTable = QAction(PlotMainWindow)
self.actionChannelTable.setObjectName('actionChannelTable')
self.actionShowLogs = QAction(PlotMainWindow)
self.actionShowLogs.setObjectName('actionShowLogs')
self.actionShowConfig = QAction(PlotMainWindow)
self.actionShowConfig.setObjectName('actionShowConfig')
self.actionReloadSchedule = QAction(PlotMainWindow)
self.actionReloadSchedule.setObjectName('actionReloadSchedule')
self.centralwidget = QWidget(PlotMainWindow)
self.centralwidget.setObjectName('centralwidget')
self.verticalLayout = QVBoxLayout(self.centralwidget)
self.verticalLayout.setSpacing(0)
self.verticalLayout.setObjectName('verticalLayout')
self.verticalLayout.setContentsMargins(2, 0, 0, 0)
self.stackedWidget = QStackedWidget(self.centralwidget)
self.stackedWidget.setObjectName('stackedWidget')
self.tabWidget = QTabWidget()
self.tabWidget.setObjectName('tabWidget')
self.treeWidget = QTreeWidget()
self.treeWidget.setObjectName('treeWidget')
self.treeWidget.setExpandsOnDoubleClick(False)
self.tabWidget.addTab(self.treeWidget, '')
self.stackedWidget.addWidget(self.tabWidget)
self.logoPage = QWidget()
self.logoPage.setObjectName('logoPage')
self.verticalLayout_3 = QVBoxLayout(self.logoPage)
self.verticalLayout_3.setSpacing(0)
self.verticalLayout_3.setObjectName('verticalLayout_3')
self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
self.verticalSpacer = QSpacerItem(0, 101, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
self.verticalLayout_3.addItem(self.verticalSpacer)
self.logoLayout = QVBoxLayout()
self.logoLayout.setObjectName('logoLayout')
self.verticalLayout_3.addLayout(self.logoLayout)
self.verticalSpacer_2 = QSpacerItem(0, 101, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
self.verticalLayout_3.addItem(self.verticalSpacer_2)
self.verticalLayout_3.setStretch(0, 1)
self.verticalLayout_3.setStretch(1, 5)
self.verticalLayout_3.setStretch(2, 1)
self.stackedWidget.addWidget(self.logoPage)
self.verticalLayout.addWidget(self.stackedWidget)
self.horizontalLayout_2 = QHBoxLayout()
self.horizontalLayout_2.setSpacing(6)
self.horizontalLayout_2.setObjectName('horizontalLayout_2')
self.horizontalLayout_2.setContentsMargins(3, -1, 3, 1)
self.warningLabel = QLabel(self.centralwidget)
self.warningLabel.setObjectName('warningLabel')
self.warningLabel.setStyleSheet('QLabel { color : red ; font-weight : bold ; font-size : 18px ; }')
self.horizontalLayout_2.addWidget(self.warningLabel)
self.uploadRateLabel = QLabel(self.centralwidget)
self.uploadRateLabel.setObjectName('uploadRateLabel')
self.uploadRateLabel.setMinimumSize(QSize(75, 25))
self.horizontalLayout_2.addWidget(self.uploadRateLabel)
self.uploadProgress = QProgressBar(self.centralwidget)
self.uploadProgress.setObjectName('uploadProgress')
sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
sizePolicy.setHorizontalStretch(0)
sizePolicy.setVerticalStretch(0)
sizePolicy.setHeightForWidth(self.uploadProgress.sizePolicy().hasHeightForWidth())
self.uploadProgress.setSizePolicy(sizePolicy)
self.uploadProgress.setMinimumSize(QSize(175, 25))
self.uploadProgress.setMaximum(5957928)
self.uploadProgress.setValue(2359296)
self.uploadProgress.setAlignment(Qt.AlignCenter)
self.horizontalLayout_2.addWidget(self.uploadProgress)
self.uploadNameLabel = QLabel(self.centralwidget)
self.uploadNameLabel.setObjectName('uploadNameLabel')
self.horizontalLayout_2.addWidget(self.uploadNameLabel)
self.horizontalSpacer_3 = QSpacerItem(0, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
self.horizontalLayout_2.addItem(self.horizontalSpacer_3)
self.activeTriggerLabel = QLabel(self.centralwidget)
self.activeTriggerLabel.setObjectName('activeTriggerLabel')
self.horizontalLayout_2.addWidget(self.activeTriggerLabel)
self.datetimeLabel = QLabel(self.centralwidget)
self.datetimeLabel.setObjectName('datetimeLabel')
sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Preferred)
sizePolicy1.setHorizontalStretch(0)
sizePolicy1.setVerticalStretch(0)
sizePolicy1.setHeightForWidth(self.datetimeLabel.sizePolicy().hasHeightForWidth())
self.datetimeLabel.setSizePolicy(sizePolicy1)
self.datetimeLabel.setMinimumSize(QSize(200, 0))
self.datetimeLabel.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
self.horizontalLayout_2.addWidget(self.datetimeLabel)
self.verticalLayout.addLayout(self.horizontalLayout_2)
PlotMainWindow.setCentralWidget(self.centralwidget)
self.menubar = QMenuBar(PlotMainWindow)
self.menubar.setObjectName('menubar')
self.menubar.setGeometry(QRect(0, 0, 1200, 22))
self.menuFile = QMenu(self.menubar)
self.menuFile.setObjectName('menuFile')
self.menuStreaming = QMenu(self.menubar)
self.menuStreaming.setObjectName('menuStreaming')
self.menuSettings = QMenu(self.menubar)
self.menuSettings.setObjectName('menuSettings')
self.menuHelp = QMenu(self.menubar)
self.menuHelp.setObjectName('menuHelp')
self.menuCheckForUpdates = QMenu(self.menuHelp)
self.menuCheckForUpdates.setObjectName('menuCheckForUpdates')
self.menuDevices = QMenu(self.menubar)
self.menuDevices.setObjectName('menuDevices')
self.menuTools = QMenu(self.menubar)
self.menuTools.setObjectName('menuTools')
self.menuMarkForUpload = QMenu(self.menuTools)
self.menuMarkForUpload.setObjectName('menuMarkForUpload')
PlotMainWindow.setMenuBar(self.menubar)
self.toolBar = QToolBar(PlotMainWindow)
self.toolBar.setObjectName('toolBar')
sizePolicy2 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Fixed)
sizePolicy2.setHorizontalStretch(0)
sizePolicy2.setVerticalStretch(0)
sizePolicy2.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
self.toolBar.setSizePolicy(sizePolicy2)
self.toolBar.setMovable(False)
self.toolBar.setIconSize(QSize(24, 24))
self.toolBar.setToolButtonStyle(Qt.ToolButtonTextBesideIcon)
self.toolBar.setFloatable(False)
PlotMainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)
self.menubar.addAction(self.menuFile.menuAction())
self.menubar.addAction(self.menuDevices.menuAction())
self.menubar.addAction(self.menuStreaming.menuAction())
self.menubar.addAction(self.menuSettings.menuAction())
self.menubar.addAction(self.menuTools.menuAction())
self.menubar.addAction(self.menuHelp.menuAction())
self.menuFile.addAction(self.actionExit)
self.menuStreaming.addAction(self.actionDisableStreaming)
self.menuStreaming.addAction(self.actionDisableArchiving)
self.menuSettings.addAction(self.actionClosableTabs)
self.menuSettings.addAction(self.actionReloadSchedule)
self.menuSettings.addAction(self.actionPreferences)
self.menuHelp.addAction(self.menuCheckForUpdates.menuAction())
self.menuHelp.addSeparator()
self.menuHelp.addAction(self.actionChannelTable)
self.menuHelp.addSeparator()
self.menuHelp.addAction(self.actionShowLogs)
self.menuHelp.addAction(self.actionShowConfig)
self.menuHelp.addSeparator()
self.menuHelp.addAction(self.actionAbout)
self.menuCheckForUpdates.addAction(self.actionUpdateLatestStable)
self.menuCheckForUpdates.addAction(self.actionUpdateCurrentBranch)
self.menuCheckForUpdates.addAction(self.actionUpdateSpecificBranch)
self.menuCheckForUpdates.addAction(self.actionUpdateSpecificCommit)
self.menuDevices.addAction(self.actionRescanUSB)
self.menuDevices.addAction(self.actionFindTCPDevices)
self.menuDevices.addAction(self.actionConnectTCPDevice)
self.menuTools.addAction(self.actionDownloadFirmware)
self.menuTools.addSeparator()
self.menuTools.addAction(self.menuMarkForUpload.menuAction())
self.menuMarkForUpload.addAction(self.actionMarkFiles)
self.menuMarkForUpload.addAction(self.actionMarkDirectory)
self.toolBar.addAction(self.actionEnableRFPower)
self.toolBar.addAction(self.actionDisableRFPower)
self.toolBar.addAction(self.actionRescanUSB)
self.toolBar.addAction(self.actionFindTCPDevices)
self.retranslateUi(PlotMainWindow)
self.actionExit.triggered.connect(PlotMainWindow.close)
self.stackedWidget.setCurrentIndex(0)
QMetaObject.connectSlotsByName(PlotMainWindow)
