# Source Generated with Decompyle++
# File: tmp_4z280k9.marshal (Python 3.11)

CHANGE_SETTINGS = enum.auto()
UPDATE_SCHEDULE_ITEM = enum.auto()
DELETE_SCHEDULE_IDS = enum.auto()
SET_RGB = enum.auto()
GET_RGB_STATE = enum.auto()
SET_LED = enum.auto()
SET_CTRL_VAR = enum.auto()
SET_DEVICE_MODE = enum.auto()
SET_RF_POWER = enum.auto()
WRITE_NVM = enum.auto()
FORCE_RESET = enum.auto()
FORCE_RUN_BOOTLOADER = enum.auto()
FORCE_RUN_APPLICATION = enum.auto()
DO_BOOTLOADER = enum.auto()
DO_HARDWARE_TESTS = enum.auto()
DO_RF_TEST = enum.auto()
DO_ACTIVE_SCAN = enum.auto()
DO_RADIO_FUNCTION = enum.auto()
ACTIVE_TRIGGERS_CHANGED = enum.auto()
_REMOTE_INFO = enum.auto()
_REMOTE_CLOSED = enum.auto()
_WAKEUP = enum.auto()
