# Source Generated with Decompyle++
# File: tmp4g3fkqu9.marshal (Python 3.11)

RECONNECTING = enum.auto()
DEVICE_INFO_START = enum.auto()
DEVICE_INFO_PROGRESS = enum.auto()
WRITE_NVM_PROGRESS = enum.auto()
DEVICE_INFO_READY = enum.auto()
STREAMING_STARTED = enum.auto()
STREAMING_ERROR_TIMEOUT = enum.auto()
STREAMING_ERROR_DISCONNECT = enum.auto()
STREAMING_ERROR_OTHER = enum.auto()
BOOTLOADER_PROGRESS = enum.auto()
BOOTLOADER_FINISHED = enum.auto()
DISCONNECTED = enum.auto()
RGB_UPDATE = enum.auto()
DEVICE_MODE_UPDATE = enum.auto()
STARTED_FILE = enum.auto()
FINISHED_FILE = enum.auto()
ONGOING_ITEMS = enum.auto()
FINISHED_ITEM = enum.auto()
HARDWARE_TEST_FUNCTION_FINISHED = enum.auto()
HARDWARE_TEST_RUN_FINISHED = enum.auto()
RF_TEST_FINISHED = enum.auto()
REMOTE_CONNECTING = enum.auto()
REMOTE_CONNECTED = enum.auto()
REMOTE_DISCONNECTED = enum.auto()
SCAN_DATA = enum.auto()
ACTIVE_SCAN_DATA = enum.auto()
SCAN_FIRST_PASS = enum.auto()
RADIO_FUNCTION_FINISHED = enum.auto()
