# Source Generated with Decompyle++
# File: tmp1vzeyaod.marshal (Python 3.11)

if not RadioPanel.objectName():
    RadioPanel.setObjectName('RadioPanel')
RadioPanel.resize(143, 278)
self.actionConnectSpecificBootloader = QAction(RadioPanel)
self.actionConnectSpecificBootloader.setObjectName('actionConnectSpecificBootloader')
self.actionConnectNoStreaming = QAction(RadioPanel)
self.actionConnectNoStreaming.setObjectName('actionConnectNoStreaming')
self.actionConnectSpecificSerial = QAction(RadioPanel)
self.actionConnectSpecificSerial.setObjectName('actionConnectSpecificSerial')
self.actionClear = QAction(RadioPanel)
self.actionClear.setObjectName('actionClear')
self.verticalLayout = QVBoxLayout(RadioPanel)
self.verticalLayout.setObjectName('verticalLayout')
self.horizontalLayout = QHBoxLayout()
self.horizontalLayout.setObjectName('horizontalLayout')
self.detailScanButton = QPushButton(RadioPanel)
self.detailScanButton.setObjectName('detailScanButton')
self.horizontalLayout.addWidget(self.detailScanButton)
self.clearButton = QToolButton(RadioPanel)
self.clearButton.setObjectName('clearButton')
self.horizontalLayout.addWidget(self.clearButton)
self.verticalLayout.addLayout(self.horizontalLayout)
self.deviceList = QListWidget(RadioPanel)
self.deviceList.setObjectName('deviceList')
self.deviceList.setContextMenuPolicy(Qt.ActionsContextMenu)
self.verticalLayout.addWidget(self.deviceList)
self.connectButton = QPushButton(RadioPanel)
self.connectButton.setObjectName('connectButton')
self.verticalLayout.addWidget(self.connectButton)
self.disconnectButton = QPushButton(RadioPanel)
self.disconnectButton.setObjectName('disconnectButton')
self.verticalLayout.addWidget(self.disconnectButton)
self.advancedMenuButton = QPushButton(RadioPanel)
self.advancedMenuButton.setObjectName('advancedMenuButton')
self.verticalLayout.addWidget(self.advancedMenuButton)
self.ctrlVarLayout = QVBoxLayout()
self.ctrlVarLayout.setObjectName('ctrlVarLayout')
self.verticalLayout.addLayout(self.ctrlVarLayout)
self.line = QFrame(RadioPanel)
self.line.setObjectName('line')
self.line.setFrameShape(QFrame.HLine)
self.line.setFrameShadow(QFrame.Sunken)
self.verticalLayout.addWidget(self.line)
self.goToRemoteButton = QPushButton(RadioPanel)
self.goToRemoteButton.setObjectName('goToRemoteButton')
self.verticalLayout.addWidget(self.goToRemoteButton)
self.retranslateUi(RadioPanel)
QMetaObject.connectSlotsByName(RadioPanel)
