# Source Generated with Decompyle++
# File: tmp2_8gl96o.marshal (Python 3.11)

self.dispatcher.controller_created.connect(self.controller_created)
self.dispatcher.controller_stopped.connect(self.remove_controller)
self.dispatcher.initial_devices_connected.connect(self.initial_devices_connected_cb)
self.actionEnableRFPower.triggered.connect(self.dispatcher.enable_all_rf_power)
self.actionDisableRFPower.triggered.connect(self.dispatcher.disable_all_rf_power)
self.dispatcher.rf_power_changed.connect(self.rf_power_changed_cb)
self.dispatcher.upload_manager_changed.connect(self.upload_manager_changed_cb)
self.dispatcher.active_triggers_changed.connect(self.active_triggers_changed)
self.actionRescanUSB.triggered.connect(self.dispatcher.rescan_usb)
self.actionFindTCPDevices.triggered.connect(self.find_tcp_devices)
self.actionConnectTCPDevice.triggered.connect(self.connect_tcp_device)
self.actionDisableStreaming.triggered.connect(self.set_disable_streaming)
self.actionDisableArchiving.triggered.connect(self.set_disable_archiving)
self.actionAbout.triggered.connect(self.show_about)
self.actionChannelTable.triggered.connect(self.show_channel_table)
self.actionPreferences.triggered.connect(self.show_preferences)
self.actionReloadSchedule.triggered.connect(self.reload_schedule_cb)
self.actionClosableTabs.triggered.connect(self.closable_tabs_cb)
self.actionShowLogs.triggered.connect(self.show_log_dir)
self.actionShowConfig.triggered.connect(self.show_config_dir)
config = self.preferences.settings.fileName()
if not os.path.exists(config):
    self.actionShowConfig.setVisible(False)
self.clock_timer = QtCore.QTimer(self)
self.clock_timer.timeout.connect(self.update_datetime_label)
self.clock_timer.start(1000)
self.upload_timeout_timer = QtCore.QTimer(self)
self.upload_timeout_timer.setSingleShot(True)
self.upload_timeout_timer.timeout.connect(self.upload_timeout_cb)
self.tabWidget.tabCloseRequested.connect(self.tab_close_requested)
self.tabWidget.currentChanged.connect(self.current_tab_changed_cb)
self.treeWidget.itemDoubleClicked.connect(self.tree_item_double_clicked)
self.actionDownloadFirmware.triggered.connect(self.download_firmware)
self.firmware_finder = hyperborea.download.FirmwareFinder(logger)
self.firmware_finder.completed.connect(self.firmware_finder_completed)
self.firmware_finder.error.connect(self.firmware_finder_error)
self.firmware_downloader = hyperborea.download.Downloader(logger)
self.firmware_downloader.update.connect(self.update_progress_cb)
self.firmware_downloader.completed.connect(self.firmware_download_completed)
self.firmware_downloader.error.connect(self.firmware_download_error)
self.actionUpdateLatestStable.triggered.connect(self.update_latest_stable)
self.actionUpdateCurrentBranch.triggered.connect(self.update_current_branch)
self.actionUpdateSpecificBranch.triggered.connect(self.update_specific_branch)
self.actionUpdateSpecificCommit.triggered.connect(self.update_specific_commit)
self.software_finder = hyperborea.download.SoftwareFinder(logger)
self.software_finder.completed.connect(self.update_finder_completed)
self.software_finder.error.connect(self.update_finder_error)
self.ref_finder = hyperborea.download.RefFinder(logger)
self.ref_finder.completed.connect(self.ref_finder_completed)
self.ref_finder.error.connect(self.ref_finder_error)
self.software_downloader = hyperborea.download.Downloader(logger)
self.software_downloader.update.connect(self.update_progress_cb)
self.software_downloader.completed.connect(self.software_download_completed)
self.software_downloader.error.connect(self.software_download_error)
self.actionMarkDirectory.triggered.connect(self.mark_directory)
self.actionMarkFiles.triggered.connect(self.mark_files)
self.next_tab_shortcut = QtGui.QShortcut(QtGui.QKeySequence('Ctrl+PgDown'), self)
self.next_tab_shortcut.activated.connect(self.next_tab)
self.prev_tab_shortcut = QtGui.QShortcut(QtGui.QKeySequence('Ctrl+PgUp'), self)
self.prev_tab_shortcut.activated.connect(self.prev_tab)
self.schedule_reader.error.connect(self.schedule_error_cb)
self.schedule_reader.warning.connect(self.schedule_warning_cb)
