# Source Generated with Decompyle++
# File: tmpad5nfq7e.marshal (Python 3.11)

self.board_button_group = QtWidgets.QButtonGroup(self)
self.board_button_group.addButton(self.boardRadioButton)
self.board_button_group.addButton(self.repoRadioButton)
self.board_button_group = QtWidgets.QButtonGroup(self)
self.board_button_group.addButton(self.branchRadioButton)
self.board_button_group.addButton(self.commitRadioButton)
self.boardRadioButton.setChecked(True)
self.branchRadioButton.setChecked(True)
self.boardRadioButton.toggled.connect(self.values_updated)
self.repoRadioButton.toggled.connect(self.values_updated)
self.branchRadioButton.toggled.connect(self.values_updated)
self.commitRadioButton.toggled.connect(self.values_updated)
self.boardName.textEdited.connect(self.values_updated)
self.repoName.textEdited.connect(self.values_updated)
self.branchName.textEdited.connect(self.values_updated)
self.commitHash.textEdited.connect(self.values_updated)
self.values_updated()
