# Source Generated with Decompyle++
# File: tmponv1uzod.marshal (Python 3.11)

if not DetailScanDialog.objectName():
    DetailScanDialog.setObjectName('DetailScanDialog')
DetailScanDialog.resize(1000, 445)
self.verticalLayout = QVBoxLayout(DetailScanDialog)
self.verticalLayout.setObjectName('verticalLayout')
self.tableWidget = QTableWidget(DetailScanDialog)
if self.tableWidget.columnCount() < 10:
    self.tableWidget.setColumnCount(10)
_Ui_DetailScanDialog__qtablewidgetitem = QTableWidgetItem()
self.tableWidget.setHorizontalHeaderItem(0, _Ui_DetailScanDialog__qtablewidgetitem)
_Ui_DetailScanDialog__qtablewidgetitem1 = QTableWidgetItem()
self.tableWidget.setHorizontalHeaderItem(1, _Ui_DetailScanDialog__qtablewidgetitem1)
_Ui_DetailScanDialog__qtablewidgetitem2 = QTableWidgetItem()
self.tableWidget.setHorizontalHeaderItem(2, _Ui_DetailScanDialog__qtablewidgetitem2)
_Ui_DetailScanDialog__qtablewidgetitem3 = QTableWidgetItem()
self.tableWidget.setHorizontalHeaderItem(3, _Ui_DetailScanDialog__qtablewidgetitem3)
_Ui_DetailScanDialog__qtablewidgetitem4 = QTableWidgetItem()
self.tableWidget.setHorizontalHeaderItem(4, _Ui_DetailScanDialog__qtablewidgetitem4)
_Ui_DetailScanDialog__qtablewidgetitem5 = QTableWidgetItem()
self.tableWidget.setHorizontalHeaderItem(5, _Ui_DetailScanDialog__qtablewidgetitem5)
_Ui_DetailScanDialog__qtablewidgetitem6 = QTableWidgetItem()
self.tableWidget.setHorizontalHeaderItem(6, _Ui_DetailScanDialog__qtablewidgetitem6)
_Ui_DetailScanDialog__qtablewidgetitem7 = QTableWidgetItem()
self.tableWidget.setHorizontalHeaderItem(7, _Ui_DetailScanDialog__qtablewidgetitem7)
_Ui_DetailScanDialog__qtablewidgetitem8 = QTableWidgetItem()
self.tableWidget.setHorizontalHeaderItem(8, _Ui_DetailScanDialog__qtablewidgetitem8)
_Ui_DetailScanDialog__qtablewidgetitem9 = QTableWidgetItem()
self.tableWidget.setHorizontalHeaderItem(9, _Ui_DetailScanDialog__qtablewidgetitem9)
self.tableWidget.setObjectName('tableWidget')
self.tableWidget.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
self.tableWidget.setEditTriggers(QAbstractItemView.NoEditTriggers)
self.tableWidget.setSelectionMode(QAbstractItemView.SingleSelection)
self.tableWidget.setSelectionBehavior(QAbstractItemView.SelectRows)
self.tableWidget.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
self.tableWidget.setSortingEnabled(True)
self.tableWidget.setCornerButtonEnabled(False)
self.tableWidget.horizontalHeader().setHighlightSections(False)
self.tableWidget.horizontalHeader().setProperty('showSortIndicator', True)
self.tableWidget.horizontalHeader().setStretchLastSection(True)
self.tableWidget.verticalHeader().setVisible(False)
self.verticalLayout.addWidget(self.tableWidget)
self.backgroundActiveScan = QCheckBox(DetailScanDialog)
self.backgroundActiveScan.setObjectName('backgroundActiveScan')
self.verticalLayout.addWidget(self.backgroundActiveScan)
self.buttonBox = QDialogButtonBox(DetailScanDialog)
self.buttonBox.setObjectName('buttonBox')
self.buttonBox.setOrientation(Qt.Horizontal)
self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel | QDialogButtonBox.Ok | QDialogButtonBox.Reset)
self.verticalLayout.addWidget(self.buttonBox)
self.retranslateUi(DetailScanDialog)
self.buttonBox.accepted.connect(DetailScanDialog.accept)
self.buttonBox.rejected.connect(DetailScanDialog.reject)
QMetaObject.connectSlotsByName(DetailScanDialog)
