# Source Generated with Decompyle++
# File: tmp6dnoc_gg.marshal (Python 3.11)

DetailScanDialog.setWindowTitle(QCoreApplication.translate('DetailScanDialog', 'Radio Scan', None))
_Ui_DetailScanDialog___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
_Ui_DetailScanDialog___qtablewidgetitem.setText(QCoreApplication.translate('DetailScanDialog', 'Serial', None))
_Ui_DetailScanDialog___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
_Ui_DetailScanDialog___qtablewidgetitem1.setText(QCoreApplication.translate('DetailScanDialog', 'Strength', None))
_Ui_DetailScanDialog___qtablewidgetitem2 = self.tableWidget.horizontalHeaderItem(2)
_Ui_DetailScanDialog___qtablewidgetitem2.setText(QCoreApplication.translate('DetailScanDialog', 'Tag 1', None))
_Ui_DetailScanDialog___qtablewidgetitem3 = self.tableWidget.horizontalHeaderItem(3)
_Ui_DetailScanDialog___qtablewidgetitem3.setText(QCoreApplication.translate('DetailScanDialog', 'Tag 2', None))
_Ui_DetailScanDialog___qtablewidgetitem4 = self.tableWidget.horizontalHeaderItem(4)
_Ui_DetailScanDialog___qtablewidgetitem4.setText(QCoreApplication.translate('DetailScanDialog', 'Board Info', None))
_Ui_DetailScanDialog___qtablewidgetitem5 = self.tableWidget.horizontalHeaderItem(5)
_Ui_DetailScanDialog___qtablewidgetitem5.setText(QCoreApplication.translate('DetailScanDialog', 'Build Info', None))
_Ui_DetailScanDialog___qtablewidgetitem6 = self.tableWidget.horizontalHeaderItem(6)
_Ui_DetailScanDialog___qtablewidgetitem6.setText(QCoreApplication.translate('DetailScanDialog', 'Build Date', None))
_Ui_DetailScanDialog___qtablewidgetitem7 = self.tableWidget.horizontalHeaderItem(7)
_Ui_DetailScanDialog___qtablewidgetitem7.setText(QCoreApplication.translate('DetailScanDialog', 'Bootloader', None))
_Ui_DetailScanDialog___qtablewidgetitem8 = self.tableWidget.horizontalHeaderItem(8)
_Ui_DetailScanDialog___qtablewidgetitem8.setText(QCoreApplication.translate('DetailScanDialog', 'Device Mode', None))
_Ui_DetailScanDialog___qtablewidgetitem9 = self.tableWidget.horizontalHeaderItem(9)
_Ui_DetailScanDialog___qtablewidgetitem9.setText(QCoreApplication.translate('DetailScanDialog', 'Last Seen', None))
self.backgroundActiveScan.setText(QCoreApplication.translate('DetailScanDialog', 'Perform active scanning in the background', None))
