# Source Generated with Decompyle++
# File: tmpxw4m048q.marshal (Python 3.11)

self.bootloader_fg_brush = QtGui.QBrush(QtGui.QColor(QtCore.Qt.GlobalColor.black))
self.bootloader_bg_brush = QtGui.QBrush(QtGui.QColor(QtCore.Qt.GlobalColor.yellow))
self.stale_fg_brush = QtGui.QBrush(QtGui.QColor(QtCore.Qt.GlobalColor.black))
self.stale_bg_brush = QtGui.QBrush(QtGui.QColor(QtCore.Qt.GlobalColor.yellow))
self.old_fg_brush = QtGui.QBrush(QtGui.QColor(QtCore.Qt.GlobalColor.black))
self.old_bg_brush = QtGui.QBrush(QtGui.QColor(QtCore.Qt.GlobalColor.red))
self.default_font = QtGui.QFont()
self.bootloader_font = QtGui.QFont()
self.bootloader_font.setBold(True)
header = self.tableWidget.horizontalHeader()
header.setSectionResizeMode(QtWidgets.QHeaderView.ResizeMode.ResizeToContents)
self.clearButton = self.buttonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Reset)
self.clearButton.setText(self.tr('Clear'))
self.clearButton.clicked.connect(self.clear_button_cb)
self.active_scan_database.cleared.connect(self.database_cleared)
self.active_scan_database.active_scan_ready.connect(self.update_active_scan_info)
self.active_scan_database.remote_connecting.connect(self.update_controller)
self.backgroundActiveScan.toggled.connect(self.set_background_active_scan)
self.backgroundActiveScan.setChecked(self.preferences.background_active_scan)
selection_model = self.tableWidget.selectionModel()
selection_model.selectionChanged.connect(self.selection_changed)
self.tableWidget.doubleClicked.connect(self.double_click_cb)
self.tableWidget.sortByColumn(0, QtCore.Qt.SortOrder.AscendingOrder)
self.tableWidget.setSortingEnabled(True)
self.update_timer = QtCore.QTimer(self)
self.update_timer.timeout.connect(self.update_rows)
self.update_timer.start(500)
self.update_scan_count()
